In [12]:
import cga_utils
import prompt_versions

import pandas as pd
import datetime
import energy

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [31]:
from langchain.globals import set_llm_cache
from langchain_community.cache import SQLiteCache

set_llm_cache(SQLiteCache(database_path=".langchain.ollama24_3_22311.db"))

In [32]:
from langchain_community.chat_models import ChatOllama
llm = ChatOllama(model="qwen3:4b", temperature = 0.0, top_p = 1, repeat_penalty=1, presence_penalty=0, frequency_penalty=0, num_predict=400)  # vagy bármely más elérhető Ollama modell

# V18 Base

In [ ]:
import pandas as pd
messages = prompt_versions.prompt_versions['V18']
messages = [(a, t.replace('/no_think','')) for (a,t)  in messages]
messages[-1] = ( messages[-1][0],  messages[-1][1] + "/no_think" ) 

start_global=datetime.datetime.now()
cga_utils.execute_dataset_predictions(llm, messages)
end_global=datetime.datetime.now()

resb = [{"prompt_version": "V18", "start_cluster": None, "end_cluster":None, "start_global":start_global, "end_global":end_global  }]
resb

1774904358.4976587

0it [00:00, ?it/s]

b2786c1a-37de-4120-b03c-32bf5c81f157
What was the change in the amount for Appliances in 2019 from 2018? Success: -94.0 3.182s
<< 680-774 || [680.0, 774.0] || [680.0, 774.0] || True >>
fe11f001-3bfe-4089-8108-412676f0a780
What was the percentage change in the amount for Appliances in 2019 from 2018? failure: -12.14 good answer:  -12.14  1.661s
<< (680-774)/774 || [680.0, 774.0, -12.144702842377262] || [680.0, 774.0, 774.0] || True >>
5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
What is the difference between the domestic and international discount rates as at September 30, 2019? failure: 2.1 good answer:  2.1  1.587s
<< 4.00 - 1.90  || [4.0, 1.9] || [4.0, 1.9] || True >>
4dc8be43-d8d9-4b08-9ffd-9c19012361ce
What is the year on year percentage change in domestic discount rate between 2018 and 2019? failure: 6.67 good answer:  6.67  1.559s
<< (4.00 - 3.75)/3.75  || [3.75, 4.0, 6.666666666666667] || [4.0, 3.75, 3.75] || True >>
6c44a1a8-0785-43a0-90ab-7e21df2c57d9
What is the year on year percentage change in international expected return on plan assets between 2018 and 2019? failure: -8.11 good answer:  -8.11  1.842s
<< (3.40 - 3.70)/3.70  || [3.7, 3.4, -8.108108108108116] || [3.4, 3.7, 3.7] || True >>
a0414f81-8dc2-44b2-a441-2c9d9c805c4d
What is the 2019 average defined contribution schemes? failure: 166.0 good answer:  172  0.859s
<< (166+178)/2 || [166.0, 1] || [166.0, 178.0] || False >>
bf7abd62-d9cd-48d2-8826-1457684019a3
What is the 2019 average defined benefit schemes? failure: 57.0 good answer:  50.5  0.761s
<< (57+44)/2 || [57.0, 1] || [57.0, 44.0] || False >>
4d259081-6da6-44bd-8830-e4de0031744c
What is the difference between 2019 average defined contribution schemes and 2019 average defined benefit schemes? failure: 109.0 good answer:  121.5  1.294s
<< [(166+178)/2] - [(57+44)/2] || [166.0, 57.0, 109.0] || [166.0, 178.0, 57.0, 44.0] || False >>
bed1fce2-69cb-4d1e-a34a-01950a1770bd
What is the percentage change in the operating loss carryforward from 2018 to 2019? Success: 26.82 1.233s
<< (73,260-57,768)/57,768 || [73260.0, 57768.0, 26.81761528874117] || [73260.0, 57768.0, 57768.0] || True >>
aea850af-68cb-4cc1-80b2-c9c2860b273e
What is the percentage change in the net deferred tax asset from 2018 to 2019? Success: 2.98 1.129s
<< (795-772)/772 || [795.0, 772.0, 2.9792746113989637] || [795.0, 772.0, 772.0] || True >>
ba6783f3-8207-419a-b407-3f688682caef
What is the ratio of IMFT’s total assets to total liabilities in 2019? Success: 2.93 1.424s
<< 2,664/909  || [2664.0, 909.0, 2.9306930693069306] || [2664.0, 909.0] || True >>
263d03ec-83d2-48df-8376-1a72167798f7
What is the proportion of IMFT’s property, plant, and equipment over total assets in 2018? failure: 87.31 good answer:  0.87  1.184s
<< 2,641/3,025  || [3025.0, 2641.0] || [2641.0, 3025.0] || True >>
78fc6d55-c20c-4f71-99fe-bc40a16e61d0
What is the change of IMFT’s total assets from 2018 to 2019? Success: -361.0 1.086s
<< 2,664 - 3,025  || [2664.0, 3025.0, -361.0] || [2664.0, 3025.0] || True >>
a4f782f1-de3b-47a3-87af-1cb33c112b39
What was the percentage change in Value added tax receivables, net, noncurrent in 2019 from 2018? Success: 14.07 1.182s
<< (592-519)/519 || [592.0, 519.0] || [592.0, 519.0, 519.0] || True >>
dc5e217a-a7b3-4fc9-ac0f-13d328f26b20
What is the 2019 average free cash flow? failure: 3923.67 good answer:  4227.5  2.166s
<< (4,411+4,044)/2 || [4411.0, 4044.0, 3316.0, 3923.6666666666665] || [4411.0, 4044.0] || True >>
7cd3aedf-1291-4fea-bc9d-a25c65727b7b
What is the 2018 average free cash flow? failure: 4044.0 good answer:  3680  0.522s
<< (4,044+3,316)/2 || [] || [4044.0, 3316.0] || False >>
22e20f25-669a-46b9-8779-2768ba391955
What is the change between 2018 and 2019 average free cash flow?[Error]name 'average_2019' is not defined
[Error]name 'average_2019' is not defined
 failure: [Error]name 'average_2019' is not defined good answer:  547.5  2.397s
<< [(4,411+4,044)/2] -[(4,044+3,316)/2] || [] || [4411.0, 4044.0, 4044.0, 3316.0] || False >>
a983501d-2eec-486d-9661-e520c7c8af5e
What was the average difference between EBITDA and underlying EBITDA for both FYs? failure: -2349.0 good answer:  3728  2.780s
<< ((85,123 - 79,046) + (63,954 - 62,575)) / 2  || [79046.0, 63954.0, 85123.0, 62575.0, -6077.0, 1379.0, -2349.0] || [85123.0, 79046.0, 63954.0, 62575.0] || True >>
64c902c6-f426-4432-84b3-c10b3065716f
What was the difference in net profit between both FYs? Success: -16458.0 1.576s
<< -9,819 - 6,639  || [-9819.0, 6639.0, -16458.0] || [6639.0] || True >>
91812b92-5e94-414f-a447-4622aa3c2d10
What was the average dividend yield for the 3 years from 2017 to 2019? failure: 1.57 good answer:  1.57  0.729s
<< (1.7%+1.5%+1.5%)/3 || [1.5666666666666667] || [1.7, 1.5, 1.5] || False >>
*** Overall EM:  0.55 / 10
29b63db7-4925-4629-b108-49bbb27fb565
What was the average risk-free interest rate over the 3 year period from 2017 to 2019? failure: 1.9 good answer:  1.9  0.528s
<< (2.7%+2.0%+1.0%)/3 || [] || [2.7, 2.0, 1.0] || False >>
*** Overall EM:  0.5714285714285714 / 10
6100c476-160a-4f1e-bfc1-a16f4cc18b52
What was the increase / (decrease) in the cost from 2018 to 2019? Success: 18.0 1.295s
<< 100 - 82 || [82.0, 100.0, 18.0] || [100.0, 82.0] || True >>
a81f1322-e74f-4e3c-a6cf-4b8d25d01cf5
What is the average Selling, general and administrative? Success: 399.33 0.838s
<< (453 + 361 + 384) / 3 || [1198.0, 3, 399.3333333333333] || [453.0, 361.0, 384.0] || False >>
f7cac790-05ae-4a55-a41d-836a6b415f88
What is the percentage increase / (decrease) of Research, development and engineering from 2018 to 2019? Success: 88.06 1.214s
<< 126 / 67 - 1 || [126.0, 67.0, 88.05970149253731] || [126.0, 67.0] || True >>
65ec782c-691e-45df-b541-caecb85154ff
What was the change in Capital redemption reserve in 2019 from 2018? Success: 0.2 2.184s
<< 0.7-0.5 || [0.7, 0.5, 0.19999999999999996] || [0.7, 0.5] || True >>
94916f79-4b6d-487f-8fa2-39f81a085760
What was the percentage change in Capital redemption reserve in 2019 from 2018? Success: 40.0 1.112s
<< (0.7-0.5)/0.5 || [0.7, 0.5, 39.99999999999999] || [0.7, 0.5, 0.5] || True >>
bbe335ff-414f-48b3-8126-5a2c7c505de3
How much was the average operating income from 2015 to 2019? Success: 13237.4 1.591s
<<  (13,535+13,264+12,913+12,604+13,871) / 5  || [13237.4] || [13535.0, 13264.0, 12913.0, 12604.0, 13871.0] || False >>
ef274d2b-fbd6-4e9f-95f9-79b37827d91c
What was the total expenses for Oracle in 2018?[Error]invalid syntax (<string>, line 24)
[Error]invalid syntax (<string>, line 24)
 failure: [Error]invalid syntax (<string>, line 24) good answer:  35796  3.742s
<< 39,383-3,587  || [] || [39383.0, 3587.0] || False >>
191c3926-7356-4ab8-a8f9-41e7b7c8a492
What were the total Assets as reported? failure: 19373.0 good answer:  64509  0.967s
<< (19,373+22,626+22,510) || [19373.0] || [19373.0, 22626.0, 22510.0] || False >>
bd2d81eb-46fc-4e62-908d-aebfccf46246
What were the total Liabilities and Stockholders' Equity as reported? failure: 62740.0 good answer:  62740  0.762s
<< (24,264+38,476) || [62740.0] || [24264.0, 38476.0] || False >>
010df393-a62e-408d-888a-045a4e435e6a
What is the difference in amount between Deferred Revenue and Other non-current liabilities as reported? failure: -14212.0 good answer:  14212  1.022s
<< (38,476-24,264) || [24264.0, 38476.0] || [38476.0, 24264.0] || True >>
58adf6c4-41ae-4f3f-84cb-cf3469a80ce4
What was the percentage change in Total Other operating expenses between 2018 and 2019? failure: -67.6 good answer:  -67.6  1.313s
<< ($166.3-$513.3)/$513.3 || [166.3, 513.3, -67.60179232417688] || [166.3, 513.3, 513.3] || True >>
79f06004-f4fc-4e82-a9fe-3c389a2f81b6
What was the change in the statutory federal income tax rate from 2018 to 2019? Success: 0.0 1.453s
<< 21.0% - 21.0% || [21.0, 21.0, 0.0] || [21.0, 21.0] || True >>
a360cee9-ce60-4f29-988d-8c6c627bb51f
What was the average State and local income tax rate, net of federal tax benefits between 2017-2019? failure: 3.0 good answer:  3  0.615s
<< (3.7 + 3.7 + 1.6) / 3 || [] || [3.7, 3.7, 1.6] || False >>
5c8c999e-354f-4693-9b2d-29e3c03cb2af
What was the change in the preferred stock disposition from 2018 to 2019?[Error]local variable 'prev_2018' referenced before assignment
[Error]local variable 'prev_2018' referenced before assignment
 failure: [Error]local variable 'prev_2018' referenced before assignment good answer:  -9.9  0.998s
<< -9.9 - 0 || [] || [] || True >>
6cc73a99-0323-40d5-9d92-b285579b3482
What was the percentage change in gross profit between 2018 and 2019? Success: -13.66 1.605s
<< (315,652-365,607)/365,607 || [365607.0, 315652.0, -13.663578651393435] || [315652.0, 365607.0, 365607.0] || True >>
fa43e8cd-7fea-4738-85ee-f61ae8529f96
What was the change in the revenues from 2018 to 2019? Success: -21.7 1.125s
<< 1,073.3 - 1,095.0 || [1073.3, 1095.0, -21.700000000000045] || [1073.3, 1095.0] || True >>
*** Overall EM:  0.5675675675675675 / 20
2067daa1-9905-456b-bcbf-42bc66b47259
What is the average net income for 2018 and 2019? Success: 88.45 1.167s
<< (106.4 + 70.5) / 2 || [106.4, 70.5, 88.45] || [106.4, 70.5] || True >>
*** Overall EM:  0.5789473684210527 / 20
a1912c87-d68c-42ea-b0da-98908097d227
What was the change in closing cash? failure: 50.7 good answer:  61.6  0.862s
<< 183.2-121.6 || [] || [183.2, 121.6] || False >>
692ea65a-9a60-4210-bd75-d34231e2e113
What is the average total current tax expense for 2017 and 2018?

In [37]:
start = pd.Timestamp(resb[0]['start_global']).tz_localize("Europe/Budapest")
end = pd.Timestamp(resb[0]['end_global']).tz_localize("Europe/Budapest")
(wh_counter, wh_gauge_sum,wh_trap, delta ) = energy.fetch_gpu_wh(start, end,  "2s")
{"prompt_version": resb[0]["prompt_version"], "start": start, "end": end, "type": "global", "wh_counter": wh_counter, "wh_trap": wh_trap,  "delta": delta, "delta_us": delta, "delta_min": delta/(1000000*60), "avg_wh_counter": (wh_counter/delta)*1000000*3600 ,"avg_wh_trap": (wh_trap/delta)*1000000*3600 }

{'prompt_version': 'V18',
 'start': Timestamp('2026-03-30 22:59:18.480723+0200', tz='Europe/Budapest'),
 'end': Timestamp('2026-03-30 23:11:07.128298+0200', tz='Europe/Budapest'),
 'type': 'global',
 'wh_counter': 82.0,
 'wh_trap': 81.87583333333333,
 'delta': 708647575.0,
 'delta_us': 708647575.0,
 'delta_min': 11.810792916666667,
 'avg_wh_counter': 416.56813684855973,
 'avg_wh_trap': 415.93735786085205}

In [36]:
resb

[{'prompt_version': 'V18',
  'start_cluster': None,
  'end_cluster': None,
  'start_global': datetime.datetime(2026, 3, 30, 22, 59, 18, 480723),
  'end_global': datetime.datetime(2026, 3, 30, 23, 11, 7, 128298)}]

# Iterations

In [39]:
runs=[('V23', 'res/e38_18.csv', 'res/errors_e38_18_cv1_4_2.csv', 11),
      ('V41', 'res/e38_23.csv', 'res/errors_e38_23_cv1_2_1.csv', 44),
      ('V43c', 'res/e38_41.csv', 'res/errors_e38_41_cv1_2_1.csv', 5 ),
      ('V29', 'res/e38_41.csv', 'res/errors_e38_41_cv1_2_1.csv', 22),
      ('V31', 'res/e38_29.csv', 'res/errors_e38_29_cv1_2_1.csv', 31),
      ('V44b', 'res/e38_29.csv', 'res/errors_e38_29_cv1_2_1.csv',15)      
     ]

In [10]:

for (prompt_version, results_file, errors_file, cluster_id) in runs:
    messages = prompt_versions.prompt_versions[prompt_version]
    messages = [(a, t.replace('/no_think','')) for (a,t)  in messages]
    messages[-1] = ( messages[-1][0],  messages[-1][1] + "/no_think" )
    print(prompt_version, "cluster Error:")
    start_cluster=datetime.datetime.now()
    cga_utils.calc_fix_mcnemar_performance(llm, messages, results_file, errors_file, cluster_id)
    end_cluster=datetime.datetime.now()
    print(prompt_version, "global Error:")
    start_global=datetime.datetime.now()
    cga_utils.execute_dataset_predictions(llm, messages)
    end_global=datetime.datetime.now()
    res.append({"prompt_version": prompt_version, "start_cluster":start_cluster, "end_cluster": end_cluster, "start_global":start_global, "end_global":end_global  })

V23 cluster Error:

0it [00:00, ?it/s]

cnt: 7
Base EM: 0.0
Base VM: 0.7142857142857143
Fix EM: 0.0
Fix VM: 0.7142857142857143
V23 global Error:
1774736768.39793

0it [00:00, ?it/s]

b2786c1a-37de-4120-b03c-32bf5c81f157
What was the change in the amount for Appliances in 2019 from 2018? Success: -94.0 1.729s
<< 680-774 || [680.0, 774.0, -94.0] || [680.0, 774.0] || True >>
fe11f001-3bfe-4089-8108-412676f0a780
What was the percentage change in the amount for Appliances in 2019 from 2018? Success: -12.14 1.704s
<< (680-774)/774 || [680.0, 774.0, -12.144702842377262] || [680.0, 774.0, 774.0] || True >>
5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
What is the difference between the domestic and international discount rates as at September 30, 2019? failure: 2.1 good answer:  2.1  1.416s
<< 4.00 - 1.90  || [4.0, 1.9, 2.1] || [4.0, 1.9] || True >>
4dc8be43-d8d9-4b08-9ffd-9c19012361ce
What is the year on year percentage change in domestic discount rate between 2018 and 2019? failure: 6.67 good answer:  6.67  1.837s
<< (4.00 - 3.75)/3.75  || [3.75, 4.0, 6.666666666666667] || [4.0, 3.75, 3.75] || True >>
6c44a1a8-0785-43a0-90ab-7e21df2c57d9
What is the year on year percentage change in international expected return on plan assets between 2018 and 2019? failure: -8.11 good answer:  -8.11  1.615s
<< (3.40 - 3.70)/3.70  || [3.7, 3.4, -8.108108108108116] || [3.4, 3.7, 3.7] || True >>
a0414f81-8dc2-44b2-a441-2c9d9c805c4d
What is the 2019 average defined contribution schemes? failure: 166.0 good answer:  172  0.982s
<< (166+178)/2 || [166.0, 1, 166.0] || [166.0, 178.0] || False >>
bf7abd62-d9cd-48d2-8826-1457684019a3
What is the 2019 average defined benefit schemes? failure: 57.0 good answer:  50.5  0.754s
<< (57+44)/2 || [57.0, 1] || [57.0, 44.0] || False >>
4d259081-6da6-44bd-8830-e4de0031744c
What is the difference between 2019 average defined contribution schemes and 2019 average defined benefit schemes? failure: 109.0 good answer:  121.5  1.200s
<< [(166+178)/2] - [(57+44)/2] || [166.0, 57.0, 109.0] || [166.0, 178.0, 57.0, 44.0] || False >>
bed1fce2-69cb-4d1e-a34a-01950a1770bd
What is the percentage change in the operating loss carryforward from 2018 to 2019? Success: 26.82 1.103s
<< (73,260-57,768)/57,768 || [73260.0, 57768.0, 26.81761528874117] || [73260.0, 57768.0, 57768.0] || True >>
aea850af-68cb-4cc1-80b2-c9c2860b273e
What is the percentage change in the net deferred tax asset from 2018 to 2019? Success: 2.98 1.124s
<< (795-772)/772 || [795.0, 772.0, 2.9792746113989637] || [795.0, 772.0, 772.0] || True >>
ba6783f3-8207-419a-b407-3f688682caef
What is the ratio of IMFT’s total assets to total liabilities in 2019? Success: 2.93 1.426s
<< 2,664/909  || [2664.0, 909.0, 2.9306930693069306] || [2664.0, 909.0] || True >>
263d03ec-83d2-48df-8376-1a72167798f7
What is the proportion of IMFT’s property, plant, and equipment over total assets in 2018? failure: 87.31 good answer:  0.87  1.260s
<< 2,641/3,025  || [3025.0, 2641.0, 87.30578512396694] || [2641.0, 3025.0] || True >>
78fc6d55-c20c-4f71-99fe-bc40a16e61d0
What is the change of IMFT’s total assets from 2018 to 2019? Success: -361.0 1.101s
<< 2,664 - 3,025  || [2664.0, 3025.0, -361.0] || [2664.0, 3025.0] || True >>
a4f782f1-de3b-47a3-87af-1cb33c112b39
What was the percentage change in Value added tax receivables, net, noncurrent in 2019 from 2018? Success: 14.07 1.258s
<< (592-519)/519 || [592.0, 519.0, 14.065510597302506] || [592.0, 519.0, 519.0] || True >>
dc5e217a-a7b3-4fc9-ac0f-13d328f26b20
What is the 2019 average free cash flow? failure: 4411.0 good answer:  4227.5  1.088s
<< (4,411+4,044)/2 || [4411.0] || [4411.0, 4044.0] || False >>
7cd3aedf-1291-4fea-bc9d-a25c65727b7b
What is the 2018 average free cash flow? failure: 4227.5 good answer:  3680  1.275s
<< (4,044+3,316)/2 || [4411.0, 4044.0, 4227.5] || [4044.0, 3316.0] || False >>
22e20f25-669a-46b9-8779-2768ba391955
What is the change between 2018 and 2019 average free cash flow? failure: 367.0 good answer:  547.5  1.174s
<< [(4,411+4,044)/2] -[(4,044+3,316)/2] || [4411.0, 4044.0, 367.0] || [4411.0, 4044.0, 4044.0, 3316.0] || False >>
a983501d-2eec-486d-9661-e520c7c8af5e
What was the average difference between EBITDA and underlying EBITDA for both FYs? failure: -2349.0 good answer:  3728  2.827s
<< ((85,123 - 79,046) + (63,954 - 62,575)) / 2  || [79046.0, 63954.0, 85123.0, 62575.0, -6077.0, 1379.0, -2349.0] || [85123.0, 79046.0, 63954.0, 62575.0] || True >>
64c902c6-f426-4432-84b3-c10b3065716f
What was the difference in net profit between both FYs? Success: -16458.0 1.190s
<< -9,819 - 6,639  || [-9819.0, 6639.0, -16458.0] || [6639.0] || True >>
91812b92-5e94-414f-a447-4622aa3c2d10
What was the average dividend yield for the 3 years from 2017 to 2019? failure: 1.57 good answer:  1.57  0.751s
<< (1.7%+1.5%+1.5%)/3 || [1.5666666666666667] || [1.7, 1.5, 1.5] || False >>
*** Overall EM:  0.6 / 10
29b63db7-4925-4629-b108-49bbb27fb565
What was the average risk-free interest rate over the 3 year period from 2017 to 2019? failure: 1.9 good answer:  1.9  0.540s
<< (2.7%+2.0%+1.0%)/3 || [1.9000000000000001] || [2.7, 2.0, 1.0] || False >>
*** Overall EM:  0.6190476190476191 / 10
6100c476-160a-4f1e-bfc1-a16f4cc18b52
What was the increase / (decrease) in the cost from 2018 to 2019? Success: 18.0 1.272s
<< 100 - 82 || [82.0, 100.0, 18.0] || [100.0, 82.0] || True >>
a81f1322-e74f-4e3c-a6cf-4b8d25d01cf5
What is the average Selling, general and administrative? Success: 399.33 0.851s
<< (453 + 361 + 384) / 3 || [1198.0, 3, 399.3333333333333] || [453.0, 361.0, 384.0] || False >>
f7cac790-05ae-4a55-a41d-836a6b415f88
What is the percentage increase / (decrease) of Research, development and engineering from 2018 to 2019? Success: 88.06 1.230s
<< 126 / 67 - 1 || [126.0, 67.0, 88.05970149253731] || [126.0, 67.0] || True >>
65ec782c-691e-45df-b541-caecb85154ff
What was the change in Capital redemption reserve in 2019 from 2018? Success: 0.2 2.216s
<< 0.7-0.5 || [0.7, 0.5, 0.19999999999999996] || [0.7, 0.5] || True >>
94916f79-4b6d-487f-8fa2-39f81a085760
What was the percentage change in Capital redemption reserve in 2019 from 2018? Success: 40.0 1.131s
<< (0.7-0.5)/0.5 || [0.7, 0.5, 39.99999999999999] || [0.7, 0.5, 0.5] || True >>
bbe335ff-414f-48b3-8126-5a2c7c505de3
How much was the average operating income from 2015 to 2019? Success: 13237.4 1.634s
<<  (13,535+13,264+12,913+12,604+13,871) / 5  || [13237.4] || [13535.0, 13264.0, 12913.0, 12604.0, 13871.0] || False >>
ef274d2b-fbd6-4e9f-95f9-79b37827d91c
What was the total expenses for Oracle in 2018? failure: 26119.0 good answer:  35796  1.958s
<< 39,383-3,587  || [39383.0, 13264.0, 3587.0, 26119.0] || [39383.0, 3587.0] || True >>
191c3926-7356-4ab8-a8f9-41e7b7c8a492
What were the total Assets as reported? failure: 22510.0 good answer:  64509  1.011s
<< (19,373+22,626+22,510) || [22510.0] || [19373.0, 22626.0, 22510.0] || False >>
bd2d81eb-46fc-4e62-908d-aebfccf46246
What were the total Liabilities and Stockholders' Equity as reported? failure: 62740.0 good answer:  62740  0.743s
<< (24,264+38,476) || [62740.0] || [24264.0, 38476.0] || False >>
010df393-a62e-408d-888a-045a4e435e6a
What is the difference in amount between Deferred Revenue and Other non-current liabilities as reported? failure: -14212.0 good answer:  14212  1.031s
<< (38,476-24,264) || [24264.0, 38476.0] || [38476.0, 24264.0] || True >>
58adf6c4-41ae-4f3f-84cb-cf3469a80ce4
What was the percentage change in Total Other operating expenses between 2018 and 2019? Success: -67.6 1.243s
<< ($166.3-$513.3)/$513.3 || [166.3, 513.3, -67.60179232417688] || [166.3, 513.3, 513.3] || True >>
79f06004-f4fc-4e82-a9fe-3c389a2f81b6
What was the change in the statutory federal income tax rate from 2018 to 2019? Success: 0.0 1.770s
<< 21.0% - 21.0% || [21.0, 21.0, 0.0] || [21.0, 21.0] || True >>
a360cee9-ce60-4f29-988d-8c6c627bb51f
What was the average State and local income tax rate, net of federal tax benefits between 2017-2019? failure: 3.0 good answer:  3  0.003s
<< (3.7 + 3.7 + 1.6) / 3 || [] || [3.7, 3.7, 1.6] || False >>
5c8c999e-354f-4693-9b2d-29e3c03cb2af
What was the change in the preferred stock disposition from 2018 to 2019?[Error]local variable 'prev_2018' referenced before assignment
[Error]local variable 'prev_2018' referenced before assignment
 failure: [Error]local variable 'prev_2018' referenced before assignment good answer:  -9.9  1.038s
<< -9.9 - 0 || [] || [] || True >>
6cc73a99-0323-40d5-9d92-b285579b3482
What was the percentage change in gross profit between 2018 and 2019? Success: -13.66 1.588s
<< (315,652-365,607)/365,607 || [365607.0, 315652.0, -13.663578651393435] || [315652.0, 365607.0, 365607.0] || True >>
fa43e8cd-7fea-4738-85ee-f61ae8529f96
What was the change in the revenues from 2018 to 2019? Success: -21.7 1.139s
<< 1,073.3 - 1,095.0 || [1073.3, 1095.0, -21.700000000000045] || [1073.3, 1095.0] || True >>
*** Overall EM:  0.6216216216216216 / 20
2067daa1-9905-456b-bcbf-42bc66b47259
What is the average net income for 2018 and 2019? Success: 88.45 1.208s
<< (106.4 + 70.5) / 2 || [106.4, 70.5, 88.45] || [106.4, 70.5] || True >>
*** Overall EM:  0.631578947368421 / 20
a1912c87-d68c-42ea-b0da-98908097d227
What was the change in closing cash? failure: 50.7 good answer:  61.6  0.877s
<< 183.2-121.6 || [] || [183.2, 121.6] || False >>
692ea65a-9a60-4210-bd75-d34231e2e113
What is the average total current tax expense for 2017 and 2018? [Error]
[Error]
 failure: [Error] good answer:  984  1.996s
<< (1,018+950)/2 || [] || [1018.0, 950.0] || False >>
7cba7400-af25-4f71-a49d-35d5eec31458
What is the average total current tax expense for 2018 and 2019?[Error]
[Error]
 failure: [Error] good answer:  1040  1.356s
<< (1,062+1,018)/2 || [] || [1062.0, 1018.0] || False >>
94ef7822-a201-493e-b557-a640f4ea4d83
What is the change in the average total current tax expense between 2017-2018, and 2018-2019?[Error]EOL while scanning string literal (<string>, line 11)
[Error]EOL while scanning string literal (<string>, line 11)
 failure: [Error]EOL while scanning string literal (<string>, line 11) good answer:  56  3.665s
<< [(1,062+1,018)/2] - [(1,018+950)/2] || [] || [1062.0, 1018.0, 1018.0, 950.0] || False >>
bfce0375-cbd0-4e25-9b82-0424058918f1
What is the total number of nonvested shares as of December 31, 2019 and 2018? failure: 12122.0 good answer:  12122  1.373s
<< 6,148+5,974 || [5974.0, 6148.0, 12122.0] || [6148.0, 5974.0] || True >>
73693527-ed4b-4d07-941e-0e654095a43d
What was the employee termination costs as a proportion of total costs in 2018? failure: 0.95 good answer:  0.9500000000000001  1.480s
<< 53.0/55.5 || [53.0, 55.5, 0.954954954954955] || [53.0, 55.5] || True >>
4a253bf4-b9fc-4ec3-b99b-d2744646a296
What was the change in Total (loan) in 2019 from 2018? Success: -56.5 1.291s
<< 828.8-885.3 || [828.8, 885.3, -56.5] || [828.8, 885.3] || True >>
74183d5d-7633-43b5-bd7b-f0894fbe2299
What was the percentage change in Total (loan) in 2019 from 2018? Success: -6.38 1.258s
<< (828.8-885.3)/885.3 || [828.8, 885.3, -6.382017395233254] || [828.8, 885.3, 885.3] || True >>
1238d807-aa57-48a3-93b6-591873788625
What was the increase / (decrease) in the Statutory federal income tax (benefit) from 2018 to 2019? failure: -19411.0 good answer:  -19411  1.771s
<< 14,694 - 34,105 || [34105.0, 14694.0, -19411.0] || [14694.0, 34105.0] || True >>
ef9d4839-5277-4614-bb73-f902fd8a38b6
What was the average Tax exempt interest income? failure: -168.0 good answer:  -168  0.625s
<< - (197 + 101 + 206) / 3 || [-168.0] || [] || True >>
fec503e8-6f91-483e-856d-bb1278bd031f
What was the percentage change in the Domestic manufacturers deduction from 2017 to 2018? Success: -162.15 1.652s
<< -2,545 / 4,095 - 1 || [4095.0, -2545.0, -162.14896214896214] || [4095.0] || True >>
a3e21403-222e-4328-8f7d-9383d2d91fe9
What is the average dividend yield in 2017 and 2018? failure: 4.4 good answer:  4.35  0.767s
<< (4.1% + 4.6%)/2  || [4.3999999999999995] || [4.1, 4.6, 2.0] || False >>
a3637ae4-b286-44a5-a115-83867e4bb14e
What is the average dividend yield in 2018 and 2019? failure: 4.55 good answer:  4.55  0.722s
<< (4.6% + 4.5%)/2  || [4.55] || [4.6, 4.5, 2.0] || False >>
d3f04ae4-ced9-446d-87b7-bb9d193e3603
What is the average expected volatility in 2017 and 2018? failure: 27.9 good answer:  27.9  1.112s
<< (27.1% + 28.7%)/2  || [27.1, 28.7, 27.9] || [27.1, 28.7, 2.0] || False >>
8b6a4479-3b77-4db7-a90c-8b1ca41a8997
What was the change in net debt from 2018 to 2019? Success: 59.4 1.120s
<< 295.2-235.8 || [295.2, 235.8, 59.39999999999998] || [295.2, 235.8] || True >>
7b2b17a9-6409-45fb-907f-270832305974
What was the percentage change in net debt from 2018 to 2019? Success: 25.19 1.205s
<< (295.2-235.8)/235.8 || [295.2, 235.8, 25.190839694656475] || [295.2, 235.8, 235.8] || True >>
3b5bb347-41c7-499a-b044-87b9a04b0833
What was the percentage change in Total Other in 2018 from 2017? Success: 15.85 1.846s
<< (95-82)/82 || [95.0, 82.0, 15.853658536585366] || [95.0, 82.0, 82.0] || True >>
*** Overall EM:  0.5818181818181818 / 30
0d0c77cf-d32c-4b0e-8da0-dcaa3f681f59
What is the percentage of Bell Wireless out of the Total BCE operating revenues in Q4 2019? Success: 39.47 1.486s
<< 2,493/6,316 || [39.47118429385687] || [2493.0, 6316.0] || False >>
259e18e8-4738-4f4d-b625-e352ca78a136
What is the increase / (decrease) in the recorded investment from 2018 to 2019? Success: -8736.0 1.229s
<< 22,446 - 31,182 || [31182.0, 22446.0, -8736.0] || [22446.0, 31182.0] || True >>
407d43ea-c405-4b88-95ae-d15b1f25fb25
What is the average Specific allowance for credit losses? Success: 198.5 1.110s
<< (177 + 220) / 2 || [177.0, 220.0, 198.5] || [177.0, 220.0] || True >>
681dcc0f-a32e-46ca-9785-1289a6aba802
What is the percentage increase / (decrease) in the Net financing receivables from 2018 to 2019? Success: -28.05 1.186s
<< 22,224 / 30,890 - 1 || [22224.0, 30890.0, -28.054386532858533] || [22224.0, 30890.0] || True >>
d2969c34-708e-4ab0-8e21-32c0b18c544c
What is the ratio of current deferred revenue to non-current deferred revenue as of end of period? Success: 1.3 1.229s
<< 4,483/3,444 || [4483.0, 3444.0, 1.301684088269454] || [4483.0, 3444.0] || True >>
59f13f19-4494-4c54-8e9a-1b499d50021a
What is the total price of shares that were exercised or canceled between 2016 and 2017? failure: -6590723.55 good answer:  981341.34  2.101s
<< (235,514*2.92)+(81,794*3.59)  || [-6590723.55, -144183.0, 3.59] || [2.92, 3.59] || False >>
b382a11b-749b-425a-a77d-20e943e00f77
What is the proportion of granted shares between 2017 and 2018 over outstanding shares at September 30, 2017? failure: 0.25 good answer:  0.11  1.037s
<< 299,397/2,845,866  || [299397.0, 409368.0, 2845866.0, 708765.0, 0.24905072831960465] || [299397.0, 2845866.0] || True >>
741f8b2e-9312-4426-893d-69b99fab247b
What is the price of outstanding shares on September 30, 2019? failure: 7.0 good answer:  11808314  0.647s
<< 1,686,902*7.00  || [] || [1686902.0, 7.0] || False >>
cf89ffee-b551-4e34-9321-30325df32cc1
What was the change in the Amount recognized in other comprehensive (loss) income from 2017 to 2018? Success: -17.0 1.291s
<< -7 - 10 || [10.0, -7.0, -17.0] || [10.0] || True >>
147f7c09-a627-4719-93ad-33661b5a4543
What was the change in Total interest expense, net presented in the consolidated statements of income in which the effects of cash flow hedges are recorded between 2017 and 2018? Success: -2.0 1.051s
<< 138-140 || [140.0, 138.0, -2.0] || [138.0, 140.0] || True >>
6a441650-9d8a-43a0-8906-bec97a73ca2c
What is the total special termination benefits charge in 2018 and 2019? Success: 21.0 1.162s
<< 6+15 || [21.0] || [6.0, 15.0] || False >>
eb1ecc18-e3d3-4dd6-a689-546998eb2784
What is the percentage change in interest cost in 2019 from 2018? Success: 11.22 1.580s
<< (436-392)/392 || [436.0, 392.0, 11.224489795918368] || [436.0, 392.0, 392.0] || True >>
8a21f821-eaf6-421a-8c67-795e7e2d1f61
What was the percentage change in Adjusted EBITDA between 2018 and 2019? Success: 16.36 1.707s
<< (108,307-93,081)/93,081 || [108307.0, 93081.0, 16.357795898196194] || [108307.0, 93081.0, 93081.0] || True >>
07ec204e-3922-4b5c-b1fd-9cb9311a53e5
What was the percentage change in the Total net deferred tax assets between 2018 and 2019? Success: -22.26 1.354s
<< (14,158-18,211)/18,211 || [18211.0, 14158.0, -22.25577947394432] || [14158.0, 18211.0, 18211.0] || True >>
f1034ee7-b182-48d5-bad8-1d9902500f57
What is the difference in the number of rights 'granted during the period' between 2018 and 2019? failure: -1226114.0 good answer:  1226114  1.118s
<< 5,691,731 - 4,465,617  || [4465617.0, 5691731.0, -1226114.0] || [5691731.0, 4465617.0] || True >>
*** Overall EM:  0.6142857142857143 / 40
545cb01f-9b10-4a1b-8a7c-e9e74e725b26
What is the average number of rights 'outstanding at end of period' for 2018 and 2019? Success: 12085176.0 1.103s
<< (13,477,758 + 10,692,594)/2  || [10692594.0, 13477758.0, 12085176.0] || [13477758.0, 10692594.0] || True >>
*** Overall EM:  0.6197183098591549 / 40
cc053817-3496-48b3-9bfc-83e9ba71bb57
What is the percentage increase in the number of rights 'outstanding at the start of period' from 2018 to 2019?  Success: 58.71 1.503s
<< (10,692,594 - 6,737,076)/6,737,076  || [6737076.0, 10692594.0, 58.712681881575925] || [10692594.0, 6737076.0, 6737076.0] || True >>
*** Overall EM:  0.625 / 40
fda3b0cb-bc87-4cbc-bc8f-79604538a700
What is the average Legal reserve within Appropriation of earnings? Success: 835623.0 0.985s
<< (707,299+963,947) / 2 || [1671246.0, 2, 835623.0] || [707299.0, 963947.0] || False >>
8d8c9fb6-6316-4fad-881e-7cdb3cfa965a
What is the increase/ (decrease) in Legal reserve within Appropriation of earnings from 2018 to 2019? Success: 256648.0 1.053s
<< 963,947-707,299 || [707299.0, 963947.0, 256648.0] || [963947.0, 707299.0] || True >>
b4aabd48-5010-425f-be30-c63f1c648c85
What is the increase/ (decrease) in Cash dividends within Appropriation of earnings from 2018 to 2019? Success: 2849050.0 1.680s
<< 9,765,155-6,916,105 || [6916105.0, 9765155.0, 2849050.0] || [9765155.0, 6916105.0] || True >>
f12806ca-aa4c-4fe6-84fc-10cefca76a9e
What is the change in the operating revenue under continuing operations from 2018 to 2019? failure: -13.0 good answer:  -22772  1.263s
<< 154,159-176,931 || [-13.0] || [154159.0, 176931.0] || False >>
f36e5912-f63c-4837-a9ed-ddbe73e5148b
What is the percentage of the operating leases of more than 5 years in the total operating leases? Success: 12.02 1.494s
<< 11,825/98,389 || [98389.0, 11825.0, 12.018619967679314] || [11825.0, 98389.0] || True >>
7ff6facd-1f7b-471c-9e38-5177c4eac9ba
What is the percentage of capital leases in the total liabilities? Success: 0.62 1.049s
<< 50,049/8,031,229 || [8031229.0, 50049.0, 0.6231798395986466] || [50049.0, 8031229.0] || True >>
d13b3204-0428-41af-8e4a-771dde352c50
What is the percentage of the purchase obligations of more than 5 years in the total purchase obligations? Success: 8.64 1.193s
<< 36,675/424,561 || [424561.0, 36675.0, 8.638334656268475] || [36675.0, 424561.0] || True >>
e1ae4755-8038-4862-9f2f-b4197f9f2159
What was the increase / (decrease) in the contractual obligation for operating leases from 2020 to 2021-2022? Success: 2968.0 1.762s
<< 7,111-4,143  || [4143.0, 7111.0, 2968.0] || [7111.0, 4143.0] || True >>
eb50d3aa-16da-4087-9ab2-10106ebd10e7
What is the average annual Operating leases contractual obligations for 2020-2024? failure: 4859.25 good answer:  2988  2.547s
<< (4,143+7,111+3,686)/5 || [4143.0, 7111.0, 3686.0, 4497.0, 19437.0, 4, 4859.25] || [4143.0, 7111.0, 3686.0] || True >>
61451090-3f7b-4fb1-b405-64a786d937d8
What was the increase / (decrease) in the asset retirement obligation from 2021-2022 to 2022-2023? Success: 100.0 1.975s
<< 250-150 || [150.0, 250.0, 100.0] || [250.0, 150.0] || True >>
56a014a9-5b9c-41e5-9523-ebbd3a01dd6d
What is the increase/ (decrease) in Statutory Audit, Certification, Audit of Individual and Consolidated Financial Statements from the period 2018 to 2019? Success: -451500.0 1.545s
<< 4,105,000-4,556,500 || [4556500.0, 4105000.0, -451500.0] || [4105000.0, 4556500.0] || True >>
2af4c7cf-79a2-4bdf-81b8-dbaff5081bc3

0it [00:00, ?it/s]

cnt: 8
Base EM: 0.0
Base VM: 0.0
Fix EM: 0.625
Fix VM: 0.625
V41 global Error:
1774737478.185137

0it [00:00, ?it/s]

b2786c1a-37de-4120-b03c-32bf5c81f157
What was the change in the amount for Appliances in 2019 from 2018? Success: -94.0 2.117s
<< 680-774 || [680.0, 774.0, -94.0] || [680.0, 774.0] || True >>
fe11f001-3bfe-4089-8108-412676f0a780
What was the percentage change in the amount for Appliances in 2019 from 2018? Success: -12.14 1.738s
<< (680-774)/774 || [680.0, 774.0, -12.144702842377262] || [680.0, 774.0, 774.0] || True >>
5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
What is the difference between the domestic and international discount rates as at September 30, 2019? failure: 2.1 good answer:  2.1  1.406s
<< 4.00 - 1.90  || [4.0, 1.9, 2.1] || [4.0, 1.9] || True >>
4dc8be43-d8d9-4b08-9ffd-9c19012361ce
What is the year on year percentage change in domestic discount rate between 2018 and 2019? failure: 6.67 good answer:  6.67  1.620s
<< (4.00 - 3.75)/3.75  || [3.75, 4.0, 6.666666666666667] || [4.0, 3.75, 3.75] || True >>
6c44a1a8-0785-43a0-90ab-7e21df2c57d9
What is the year on year percentage change in international expected return on plan assets between 2018 and 2019? failure: -8.11 good answer:  -8.11  1.670s
<< (3.40 - 3.70)/3.70  || [3.7, 3.4, -8.108108108108116] || [3.4, 3.7, 3.7] || True >>
a0414f81-8dc2-44b2-a441-2c9d9c805c4d
What is the 2019 average defined contribution schemes? failure: 166.0 good answer:  172  1.010s
<< (166+178)/2 || [166.0, 1, 166.0] || [166.0, 178.0] || False >>
bf7abd62-d9cd-48d2-8826-1457684019a3
What is the 2019 average defined benefit schemes? failure: 57.0 good answer:  50.5  0.780s
<< (57+44)/2 || [57.0, 1] || [57.0, 44.0] || False >>
4d259081-6da6-44bd-8830-e4de0031744c
What is the difference between 2019 average defined contribution schemes and 2019 average defined benefit schemes? failure: 109.0 good answer:  121.5  1.322s
<< [(166+178)/2] - [(57+44)/2] || [166.0, 57.0, 109.0] || [166.0, 178.0, 57.0, 44.0] || False >>
bed1fce2-69cb-4d1e-a34a-01950a1770bd
What is the percentage change in the operating loss carryforward from 2018 to 2019? Success: 26.82 1.276s
<< (73,260-57,768)/57,768 || [73260.0, 57768.0, 26.81761528874117] || [73260.0, 57768.0, 57768.0] || True >>
aea850af-68cb-4cc1-80b2-c9c2860b273e
What is the percentage change in the net deferred tax asset from 2018 to 2019? Success: 2.98 1.158s
<< (795-772)/772 || [795.0, 772.0, 0.029792746113989636] || [795.0, 772.0, 772.0] || True >>
ba6783f3-8207-419a-b407-3f688682caef
What is the ratio of IMFT’s total assets to total liabilities in 2019? Success: 2.93 1.469s
<< 2,664/909  || [2664.0, 909.0, 2.9306930693069306] || [2664.0, 909.0] || True >>
263d03ec-83d2-48df-8376-1a72167798f7
What is the proportion of IMFT’s property, plant, and equipment over total assets in 2018? failure: 87.31 good answer:  0.87  1.287s
<< 2,641/3,025  || [3025.0, 2641.0, 87.30578512396694] || [2641.0, 3025.0] || True >>
78fc6d55-c20c-4f71-99fe-bc40a16e61d0
What is the change of IMFT’s total assets from 2018 to 2019? Success: -361.0 1.127s
<< 2,664 - 3,025  || [2664.0, 3025.0, -361.0] || [2664.0, 3025.0] || True >>
a4f782f1-de3b-47a3-87af-1cb33c112b39
What was the percentage change in Value added tax receivables, net, noncurrent in 2019 from 2018? Success: 14.07 1.276s
<< (592-519)/519 || [592.0, 519.0, 14.065510597302506] || [592.0, 519.0, 519.0] || True >>
dc5e217a-a7b3-4fc9-ac0f-13d328f26b20
What is the 2019 average free cash flow? failure: 4411.0 good answer:  4227.5  1.116s
<< (4,411+4,044)/2 || [4411.0] || [4411.0, 4044.0] || False >>
7cd3aedf-1291-4fea-bc9d-a25c65727b7b
What is the 2018 average free cash flow? failure: 4044.0 good answer:  3680  0.535s
<< (4,044+3,316)/2 || [] || [4044.0, 3316.0] || False >>
22e20f25-669a-46b9-8779-2768ba391955
What is the change between 2018 and 2019 average free cash flow? failure: 367.0 good answer:  547.5  1.196s
<< [(4,411+4,044)/2] -[(4,044+3,316)/2] || [4411.0, 4044.0, 367.0] || [4411.0, 4044.0, 4044.0, 3316.0] || False >>
a983501d-2eec-486d-9661-e520c7c8af5e
What was the average difference between EBITDA and underlying EBITDA for both FYs? failure: -2349.0 good answer:  3728  2.852s
<< ((85,123 - 79,046) + (63,954 - 62,575)) / 2  || [79046.0, 63954.0, 85123.0, 62575.0, -6077.0, 1379.0, -2349.0] || [85123.0, 79046.0, 63954.0, 62575.0] || True >>
64c902c6-f426-4432-84b3-c10b3065716f
What was the difference in net profit between both FYs? Success: -16458.0 1.215s
<< -9,819 - 6,639  || [-9819.0, 6639.0, -16458.0] || [6639.0] || True >>
91812b92-5e94-414f-a447-4622aa3c2d10
What was the average dividend yield for the 3 years from 2017 to 2019? failure: 1.57 good answer:  1.57  0.760s
<< (1.7%+1.5%+1.5%)/3 || [1.5666666666666667] || [1.7, 1.5, 1.5] || False >>
*** Overall EM:  0.6 / 10
29b63db7-4925-4629-b108-49bbb27fb565
What was the average risk-free interest rate over the 3 year period from 2017 to 2019? failure: 1.9 good answer:  1.9  1.659s
<< (2.7%+2.0%+1.0%)/3 || [1.0, 2.0, 2.7, 1.9000000000000001] || [2.7, 2.0, 1.0] || True >>
*** Overall EM:  0.6190476190476191 / 10
6100c476-160a-4f1e-bfc1-a16f4cc18b52
What was the increase / (decrease) in the cost from 2018 to 2019? Success: 18.0 1.286s
<< 100 - 82 || [82.0, 100.0, 18.0] || [100.0, 82.0] || True >>
a81f1322-e74f-4e3c-a6cf-4b8d25d01cf5
What is the average Selling, general and administrative? Success: 399.33 0.863s
<< (453 + 361 + 384) / 3 || [1198.0, 3, 399.3333333333333] || [453.0, 361.0, 384.0] || False >>
f7cac790-05ae-4a55-a41d-836a6b415f88
What is the percentage increase / (decrease) of Research, development and engineering from 2018 to 2019? Success: 88.06 1.243s
<< 126 / 67 - 1 || [126.0, 67.0, 88.05970149253731] || [126.0, 67.0] || True >>
65ec782c-691e-45df-b541-caecb85154ff
What was the change in Capital redemption reserve in 2019 from 2018? Success: 0.2 2.228s
<< 0.7-0.5 || [0.7, 0.5, 0.19999999999999996] || [0.7, 0.5] || True >>
94916f79-4b6d-487f-8fa2-39f81a085760
What was the percentage change in Capital redemption reserve in 2019 from 2018? Success: 40.0 1.146s
<< (0.7-0.5)/0.5 || [0.7, 0.5, 39.99999999999999] || [0.7, 0.5, 0.5] || True >>
bbe335ff-414f-48b3-8126-5a2c7c505de3
How much was the average operating income from 2015 to 2019? Success: 13237.4 1.645s
<<  (13,535+13,264+12,913+12,604+13,871) / 5  || [13237.4] || [13535.0, 13264.0, 12913.0, 12604.0, 13871.0] || False >>
ef274d2b-fbd6-4e9f-95f9-79b37827d91c
What was the total expenses for Oracle in 2018? failure: 39383.0 good answer:  35796  0.624s
<< 39,383-3,587  || [] || [39383.0, 3587.0] || False >>
191c3926-7356-4ab8-a8f9-41e7b7c8a492
What were the total Assets as reported? failure: 22510.0 good answer:  64509  1.009s
<< (19,373+22,626+22,510) || [22510.0] || [19373.0, 22626.0, 22510.0] || False >>
bd2d81eb-46fc-4e62-908d-aebfccf46246
What were the total Liabilities and Stockholders' Equity as reported? failure: 62740.0 good answer:  62740  0.750s
<< (24,264+38,476) || [62740.0] || [24264.0, 38476.0] || False >>
010df393-a62e-408d-888a-045a4e435e6a
What is the difference in amount between Deferred Revenue and Other non-current liabilities as reported? failure: -14212.0 good answer:  14212  1.130s
<< (38,476-24,264) || [24264.0, 38476.0, -14212.0] || [38476.0, 24264.0] || True >>
58adf6c4-41ae-4f3f-84cb-cf3469a80ce4
What was the percentage change in Total Other operating expenses between 2018 and 2019? Success: -67.6 1.263s
<< ($166.3-$513.3)/$513.3 || [166.3, 513.3, -67.60179232417688] || [166.3, 513.3, 513.3] || True >>
79f06004-f4fc-4e82-a9fe-3c389a2f81b6
What was the change in the statutory federal income tax rate from 2018 to 2019? Success: 0.0 1.645s
<< 21.0% - 21.0% || [21.0, 21.0, 0.0] || [21.0, 21.0] || True >>
a360cee9-ce60-4f29-988d-8c6c627bb51f
What was the average State and local income tax rate, net of federal tax benefits between 2017-2019? failure: 3.0 good answer:  3  0.646s
<< (3.7 + 3.7 + 1.6) / 3 || [] || [3.7, 3.7, 1.6] || False >>
5c8c999e-354f-4693-9b2d-29e3c03cb2af
What was the change in the preferred stock disposition from 2018 to 2019?[Error]local variable 'value_2018' referenced before assignment
[Error]local variable 'value_2018' referenced before assignment
 failure: [Error]local variable 'value_2018' referenced before assignment good answer:  -9.9  0.987s
<< -9.9 - 0 || [] || [] || True >>
6cc73a99-0323-40d5-9d92-b285579b3482
What was the percentage change in gross profit between 2018 and 2019? Success: -13.66 1.610s
<< (315,652-365,607)/365,607 || [365607.0, 315652.0, -13.663578651393435] || [315652.0, 365607.0, 365607.0] || True >>
fa43e8cd-7fea-4738-85ee-f61ae8529f96
What was the change in the revenues from 2018 to 2019? Success: -21.7 1.244s
<< 1,073.3 - 1,095.0 || [1073.3, 1095.0, -21.700000000000045] || [1073.3, 1095.0] || True >>
*** Overall EM:  0.6216216216216216 / 20
2067daa1-9905-456b-bcbf-42bc66b47259
What is the average net income for 2018 and 2019? Success: 88.45 1.219s
<< (106.4 + 70.5) / 2 || [106.4, 70.5, 88.45] || [106.4, 70.5] || True >>
*** Overall EM:  0.631578947368421 / 20
a1912c87-d68c-42ea-b0da-98908097d227
What was the change in closing cash? failure: 50.7 good answer:  61.6  0.897s
<< 183.2-121.6 || [] || [183.2, 121.6] || False >>
692ea65a-9a60-4210-bd75-d34231e2e113
What is the average total current tax expense for 2017 and 2018? [Error]
[Error]
 failure: [Error] good answer:  984  2.013s
<< (1,018+950)/2 || [] || [1018.0, 950.0] || False >>
7cba7400-af25-4f71-a49d-35d5eec31458
What is the average total current tax expense for 2018 and 2019?[Error]
[Error]
 failure: [Error] good answer:  1040  1.361s
<< (1,062+1,018)/2 || [] || [1062.0, 1018.0] || False >>
94ef7822-a201-493e-b557-a640f4ea4d83
What is the change in the average total current tax expense between 2017-2018, and 2018-2019?[Error]EOL while scanning string literal (<string>, line 11)
[Error]EOL while scanning string literal (<string>, line 11)
 failure: [Error]EOL while scanning string literal (<string>, line 11) good answer:  56  3.705s
<< [(1,062+1,018)/2] - [(1,018+950)/2] || [] || [1062.0, 1018.0, 1018.0, 950.0] || False >>
bfce0375-cbd0-4e25-9b82-0424058918f1
What is the total number of nonvested shares as of December 31, 2019 and 2018? failure: 12122.0 good answer:  12122  1.323s
<< 6,148+5,974 || [5974.0, 6148.0, 12122.0] || [6148.0, 5974.0] || True >>
73693527-ed4b-4d07-941e-0e654095a43d
What was the employee termination costs as a proportion of total costs in 2018? failure: 0.95 good answer:  0.9500000000000001  1.487s
<< 53.0/55.5 || [53.0, 55.5, 0.954954954954955] || [53.0, 55.5] || True >>
4a253bf4-b9fc-4ec3-b99b-d2744646a296
What was the change in Total (loan) in 2019 from 2018? Success: -56.5 1.362s
<< 828.8-885.3 || [828.8, 885.3, -56.5] || [828.8, 885.3] || True >>
74183d5d-7633-43b5-bd7b-f0894fbe2299
What was the percentage change in Total (loan) in 2019 from 2018? Success: -6.38 1.330s
<< (828.8-885.3)/885.3 || [828.8, 885.3, -6.382017395233254] || [828.8, 885.3, 885.3] || True >>
1238d807-aa57-48a3-93b6-591873788625
What was the increase / (decrease) in the Statutory federal income tax (benefit) from 2018 to 2019? Success: -19411.0 2.456s
<< 14,694 - 34,105 || [34105.0, 14694.0, -19411.0, -19411.0] || [14694.0, 34105.0] || True >>
ef9d4839-5277-4614-bb73-f902fd8a38b6
What was the average Tax exempt interest income? failure: -168.0 good answer:  -168  0.636s
<< - (197 + 101 + 206) / 3 || [-168.0] || [] || True >>
fec503e8-6f91-483e-856d-bb1278bd031f
What was the percentage change in the Domestic manufacturers deduction from 2017 to 2018? Success: -162.15 1.747s
<< -2,545 / 4,095 - 1 || [4095.0, -2545.0, -162.15] || [4095.0] || True >>
a3e21403-222e-4328-8f7d-9383d2d91fe9
What is the average dividend yield in 2017 and 2018? failure: 4.4 good answer:  4.35  0.780s
<< (4.1% + 4.6%)/2  || [4.3999999999999995] || [4.1, 4.6, 2.0] || False >>
a3637ae4-b286-44a5-a115-83867e4bb14e
What is the average dividend yield in 2018 and 2019? failure: 4.55 good answer:  4.55  0.791s
<< (4.6% + 4.5%)/2  || [4.55] || [4.6, 4.5, 2.0] || False >>
d3f04ae4-ced9-446d-87b7-bb9d193e3603
What is the average expected volatility in 2017 and 2018? failure: 27.9 good answer:  27.9  1.112s
<< (27.1% + 28.7%)/2  || [27.1, 28.7, 27.9] || [27.1, 28.7, 2.0] || False >>
8b6a4479-3b77-4db7-a90c-8b1ca41a8997
What was the change in net debt from 2018 to 2019? Success: 59.4 1.141s
<< 295.2-235.8 || [295.2, 235.8, 59.39999999999998] || [295.2, 235.8] || True >>
7b2b17a9-6409-45fb-907f-270832305974
What was the percentage change in net debt from 2018 to 2019? Success: 25.19 1.210s
<< (295.2-235.8)/235.8 || [295.2, 235.8, 25.190839694656475] || [295.2, 235.8, 235.8] || True >>
3b5bb347-41c7-499a-b044-87b9a04b0833
What was the percentage change in Total Other in 2018 from 2017? Success: 15.85 1.848s
<< (95-82)/82 || [95.0, 82.0, 15.853658536585366] || [95.0, 82.0, 82.0] || True >>
*** Overall EM:  0.6 / 30
0d0c77cf-d32c-4b0e-8da0-dcaa3f681f59
What is the percentage of Bell Wireless out of the Total BCE operating revenues in Q4 2019? Success: 39.47 1.492s
<< 2,493/6,316 || [39.47118429385687] || [2493.0, 6316.0] || False >>
259e18e8-4738-4f4d-b625-e352ca78a136
What is the increase / (decrease) in the recorded investment from 2018 to 2019? Success: -8736.0 1.245s
<< 22,446 - 31,182 || [31182.0, 22446.0, -8736.0] || [22446.0, 31182.0] || True >>
407d43ea-c405-4b88-95ae-d15b1f25fb25
What is the average Specific allowance for credit losses? Success: 198.5 1.135s
<< (177 + 220) / 2 || [177.0, 220.0, 198.5] || [177.0, 220.0] || True >>
681dcc0f-a32e-46ca-9785-1289a6aba802
What is the percentage increase / (decrease) in the Net financing receivables from 2018 to 2019? Success: -28.05 1.206s
<< 22,224 / 30,890 - 1 || [22224.0, 30890.0, -28.054386532858533] || [22224.0, 30890.0] || True >>
d2969c34-708e-4ab0-8e21-32c0b18c544c
What is the ratio of current deferred revenue to non-current deferred revenue as of end of period? Success: 1.3 1.246s
<< 4,483/3,444 || [4483.0, 3444.0, 1.301684088269454] || [4483.0, 3444.0] || True >>
59f13f19-4494-4c54-8e9a-1b499d50021a
What is the total price of shares that were exercised or canceled between 2016 and 2017?[Error]'weighted_average_exercise_price_per_share'
[Error]'weighted_average_exercise_price_per_share'
 failure: [Error]'weighted_average_exercise_price_per_share' good answer:  981341.34  1.295s
<< (235,514*2.92)+(81,794*3.59)  || [] || [2.92, 3.59] || False >>
b382a11b-749b-425a-a77d-20e943e00f77
What is the proportion of granted shares between 2017 and 2018 over outstanding shares at September 30, 2017? failure: 0.25 good answer:  0.11  1.031s
<< 299,397/2,845,866  || [299397.0, 409368.0, 2845866.0, 708765.0, 0.24905072831960465] || [299397.0, 2845866.0] || True >>
741f8b2e-9312-4426-893d-69b99fab247b
What is the price of outstanding shares on September 30, 2019? failure: 7.0 good answer:  11808314  0.660s
<< 1,686,902*7.00  || [] || [1686902.0, 7.0] || False >>
cf89ffee-b551-4e34-9321-30325df32cc1
What was the change in the Amount recognized in other comprehensive (loss) income from 2017 to 2018? Success: -17.0 1.816s
<< -7 - 10 || [10.0, -7.0, -17.0] || [10.0] || True >>
147f7c09-a627-4719-93ad-33661b5a4543
What was the change in Total interest expense, net presented in the consolidated statements of income in which the effects of cash flow hedges are recorded between 2017 and 2018? Success: -2.0 1.757s
<< 138-140 || [140.0, 138.0, -2.0] || [138.0, 140.0] || True >>
6a441650-9d8a-43a0-8906-bec97a73ca2c
What is the total special termination benefits charge in 2018 and 2019? Success: 21.0 1.201s
<< 6+15 || [21.0] || [6.0, 15.0] || False >>
eb1ecc18-e3d3-4dd6-a689-546998eb2784
What is the percentage change in interest cost in 2019 from 2018? Success: 11.22 1.475s
<< (436-392)/392 || [436.0, 392.0, 11.224489795918368] || [436.0, 392.0, 392.0] || True >>
8a21f821-eaf6-421a-8c67-795e7e2d1f61
What was the percentage change in Adjusted EBITDA between 2018 and 2019? Success: 16.36 1.730s
<< (108,307-93,081)/93,081 || [108307.0, 93081.0, 16.357795898196194] || [108307.0, 93081.0, 93081.0] || True >>
07ec204e-3922-4b5c-b1fd-9cb9311a53e5
What was the percentage change in the Total net deferred tax assets between 2018 and 2019? Success: -22.26 1.676s
<< (14,158-18,211)/18,211 || [18211.0, 14158.0, -22.25577947394432] || [14158.0, 18211.0, 18211.0] || True >>
f1034ee7-b182-48d5-bad8-1d9902500f57
What is the difference in the number of rights 'granted during the period' between 2018 and 2019? failure: -1226114.0 good answer:  1226114  1.127s
<< 5,691,731 - 4,465,617  || [5691731.0, 4465617.0, -1226114.0] || [5691731.0, 4465617.0] || True >>
*** Overall EM:  0.6285714285714286 / 40
545cb01f-9b10-4a1b-8a7c-e9e74e725b26
What is the average number of rights 'outstanding at end of period' for 2018 and 2019? Success: 12085176.0 1.122s
<< (13,477,758 + 10,692,594)/2  || [10692594.0, 13477758.0, 12085176.0] || [13477758.0, 10692594.0] || True >>
*** Overall EM:  0.6338028169014085 / 40
cc053817-3496-48b3-9bfc-83e9ba71bb57
What is the percentage increase in the number of rights 'outstanding at the start of period' from 2018 to 2019?  Success: 58.71 1.541s
<< (10,692,594 - 6,737,076)/6,737,076  || [6737076.0, 10692594.0, 58.712681881575925] || [10692594.0, 6737076.0, 6737076.0] || True >>
*** Overall EM:  0.6388888888888888 / 40
fda3b0cb-bc87-4cbc-bc8f-79604538a700
What is the average Legal reserve within Appropriation of earnings? Success: 835623.0 1.000s
<< (707,299+963,947) / 2 || [1671246.0, 2, 835623.0] || [707299.0, 963947.0] || False >>
8d8c9fb6-6316-4fad-881e-7cdb3cfa965a
What is the increase/ (decrease) in Legal reserve within Appropriation of earnings from 2018 to 2019? Success: 256648.0 1.059s
<< 963,947-707,299 || [707299.0, 963947.0, 256648.0] || [963947.0, 707299.0] || True >>
b4aabd48-5010-425f-be30-c63f1c648c85
What is the increase/ (decrease) in Cash dividends within Appropriation of earnings from 2018 to 2019? Success: 2849050.0 1.549s
<< 9,765,155-6,916,105 || [6916105.0, 9765155.0, 2849050.0] || [9765155.0, 6916105.0] || True >>
f12806ca-aa4c-4fe6-84fc-10cefca76a9e
What is the change in the operating revenue under continuing operations from 2018 to 2019? failure: -13.0 good answer:  -22772  1.214s
<< 154,159-176,931 || [] || [154159.0, 176931.0] || False >>
f36e5912-f63c-4837-a9ed-ddbe73e5148b
What is the percentage of the operating leases of more than 5 years in the total operating leases? Success: 12.02 1.491s
<< 11,825/98,389 || [98389.0, 11825.0, 12.018619967679314] || [11825.0, 98389.0] || True >>
7ff6facd-1f7b-471c-9e38-5177c4eac9ba
What is the percentage of capital leases in the total liabilities? Success: 0.62 1.050s
<< 50,049/8,031,229 || [8031229.0, 50049.0, 0.6231798395986466] || [50049.0, 8031229.0] || True >>
d13b3204-0428-41af-8e4a-771dde352c50
What is the percentage of the purchase obligations of more than 5 years in the total purchase obligations? Success: 8.64 1.180s
<< 36,675/424,561 || [424561.0, 36675.0, 8.638334656268475] || [36675.0, 424561.0] || True >>
e1ae4755-8038-4862-9f2f-b4197f9f2159
What was the increase / (decrease) in the contractual obligation for operating leases from 2020 to 2021-2022? Success: 2968.0 1.376s
<< 7,111-4,143  || [4143.0, 7111.0, 2968.0] || [7111.0, 4143.0] || True >>
eb50d3aa-16da-4087-9ab2-10106ebd10e7
What is the average annual Operating leases contractual obligations for 2020-2024? failure: 4859.25 good answer:  2988  2.497s
<< (4,143+7,111+3,686)/5 || [4143.0, 7111.0, 3686.0, 4497.0, 19437.0, 4859.25] || [4143.0, 7111.0, 3686.0] || True >>
61451090-3f7b-4fb1-b405-64a786d937d8
What was the increase / (decrease) in the asset retirement obligation from 2021-2022 to 2022-2023? Success: 100.0 1.788s
<< 250-150 || [150.0, 250.0, 100.0] || [250.0, 150.0] || True >>
56a014a9-5b9c-41e5-9523-ebbd3a01dd6d
What is the increase/ (decrease) in Statutory Audit, Certification, Audit of Individual and Consolidated Financial Statements from the period 2018 to 2019? Success: -451500.0 2.020s
<< 4,105,000-4,556,500 || [4556500.0, 4105000.0, -451500.0] || [4105000.0, 4556500.0] || True >>
2af4c7cf-79a2-4bdf-81b8-dbaff5081bc3

0it [00:00, ?it/s]

[Inner Exception]cannot unpack non-iterable NoneType object
cnt: 10
Base EM: 0.0
Base VM: 0.0
Fix EM: 0.2
Fix VM: 0.3
V43c global Error:
1774738194.7591226

0it [00:00, ?it/s]

b2786c1a-37de-4120-b03c-32bf5c81f157
What was the change in the amount for Appliances in 2019 from 2018? Success: -94.0 2.116s
<< 680-774 || [680.0, 774.0, -94.0] || [680.0, 774.0] || True >>
fe11f001-3bfe-4089-8108-412676f0a780
What was the percentage change in the amount for Appliances in 2019 from 2018? Success: -12.14 1.757s
<< (680-774)/774 || [680.0, 774.0, -12.144702842377262] || [680.0, 774.0, 774.0] || True >>
5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
What is the difference between the domestic and international discount rates as at September 30, 2019? failure: -2.1 good answer:  2.1  1.494s
<< 4.00 - 1.90  || [4.0, 1.9] || [4.0, 1.9] || True >>
4dc8be43-d8d9-4b08-9ffd-9c19012361ce
What is the year on year percentage change in domestic discount rate between 2018 and 2019? failure: 6.67 good answer:  6.67  1.570s
<< (4.00 - 3.75)/3.75  || [3.75, 4.0] || [4.0, 3.75, 3.75] || True >>
6c44a1a8-0785-43a0-90ab-7e21df2c57d9
What is the year on year percentage change in international expected return on plan assets between 2018 and 2019? failure: -8.11 good answer:  -8.11  1.674s
<< (3.40 - 3.70)/3.70  || [3.7, 3.4, -8.108108108108116] || [3.4, 3.7, 3.7] || True >>
a0414f81-8dc2-44b2-a441-2c9d9c805c4d
What is the 2019 average defined contribution schemes? failure: 55.33 good answer:  172  1.035s
<< (166+178)/2 || [166.0, 55.333333333333336] || [166.0, 178.0] || False >>
bf7abd62-d9cd-48d2-8826-1457684019a3
What is the 2019 average defined benefit schemes? failure: 57.0 good answer:  50.5  0.911s
<< (57+44)/2 || [57.0, 1, 57.0] || [57.0, 44.0] || False >>
4d259081-6da6-44bd-8830-e4de0031744c
What is the difference between 2019 average defined contribution schemes and 2019 average defined benefit schemes? failure: 109.0 good answer:  121.5  1.347s
<< [(166+178)/2] - [(57+44)/2] || [166.0, 57.0, 109.0] || [166.0, 178.0, 57.0, 44.0] || False >>
bed1fce2-69cb-4d1e-a34a-01950a1770bd
What is the percentage change in the operating loss carryforward from 2018 to 2019? Success: 26.82 1.243s
<< (73,260-57,768)/57,768 || [73260.0, 57768.0, 26.81761528874117] || [73260.0, 57768.0, 57768.0] || True >>
aea850af-68cb-4cc1-80b2-c9c2860b273e
What is the percentage change in the net deferred tax asset from 2018 to 2019?[Error]local variable 'previous_value' referenced before assignment
[Error]local variable 'previous_value' referenced before assignment
 failure: [Error]local variable 'previous_value' referenced before assignment good answer:  2.98  1.018s
<< (795-772)/772 || [] || [795.0, 772.0, 772.0] || False >>
ba6783f3-8207-419a-b407-3f688682caef
What is the ratio of IMFT’s total assets to total liabilities in 2019? Success: 2.93 1.463s
<< 2,664/909  || [2664.0, 909.0, 2.9306930693069306] || [2664.0, 909.0] || True >>
263d03ec-83d2-48df-8376-1a72167798f7
What is the proportion of IMFT’s property, plant, and equipment over total assets in 2018? failure: 87.31 good answer:  0.87  1.298s
<< 2,641/3,025  || [3025.0, 2641.0, 87.30578512396694] || [2641.0, 3025.0] || True >>
78fc6d55-c20c-4f71-99fe-bc40a16e61d0
What is the change of IMFT’s total assets from 2018 to 2019? Success: -361.0 1.095s
<< 2,664 - 3,025  || [2664.0, 3025.0, -361.0] || [2664.0, 3025.0] || True >>
a4f782f1-de3b-47a3-87af-1cb33c112b39
What was the percentage change in Value added tax receivables, net, noncurrent in 2019 from 2018? Success: 14.07 1.287s
<< (592-519)/519 || [592.0, 519.0, 14.065510597302506] || [592.0, 519.0, 519.0] || True >>
dc5e217a-a7b3-4fc9-ac0f-13d328f26b20
What is the 2019 average free cash flow? failure: 3923.67 good answer:  4227.5  2.139s
<< (4,411+4,044)/2 || [4411.0, 4044.0, 3316.0, 3923.6666666666665] || [4411.0, 4044.0] || True >>
7cd3aedf-1291-4fea-bc9d-a25c65727b7b
What is the 2018 average free cash flow? failure: 4044.0 good answer:  3680  0.548s
<< (4,044+3,316)/2 || [] || [4044.0, 3316.0] || False >>
22e20f25-669a-46b9-8779-2768ba391955
What is the change between 2018 and 2019 average free cash flow? failure: 26.0 good answer:  547.5  1.699s
<< [(4,411+4,044)/2] -[(4,044+3,316)/2] || [5443.0, 5417.0, 26.0] || [4411.0, 4044.0, 4044.0, 3316.0] || False >>
a983501d-2eec-486d-9661-e520c7c8af5e
What was the average difference between EBITDA and underlying EBITDA for both FYs? failure: 2349.0 good answer:  3728  2.859s
<< ((85,123 - 79,046) + (63,954 - 62,575)) / 2  || [79046.0, 63954.0, 85123.0, 62575.0, 6077.0, -1379.0, 2349.0] || [85123.0, 79046.0, 63954.0, 62575.0] || True >>
64c902c6-f426-4432-84b3-c10b3065716f
What was the difference in net profit between both FYs? Success: -16458.0 1.152s
<< -9,819 - 6,639  || [-9819.0, 6639.0] || [6639.0] || True >>
91812b92-5e94-414f-a447-4622aa3c2d10
What was the average dividend yield for the 3 years from 2017 to 2019? failure: 1.57 good answer:  1.57  0.667s
<< (1.7%+1.5%+1.5%)/3 || [] || [1.7, 1.5, 1.5] || False >>
*** Overall EM:  0.5 / 10
29b63db7-4925-4629-b108-49bbb27fb565
What was the average risk-free interest rate over the 3 year period from 2017 to 2019? failure: 1.9 good answer:  1.9  0.552s
<< (2.7%+2.0%+1.0%)/3 || [] || [2.7, 2.0, 1.0] || False >>
*** Overall EM:  0.5238095238095238 / 10
6100c476-160a-4f1e-bfc1-a16f4cc18b52
What was the increase / (decrease) in the cost from 2018 to 2019? Success: 18.0 1.670s
<< 100 - 82 || [82.0, 100.0, 18.0] || [100.0, 82.0] || True >>
a81f1322-e74f-4e3c-a6cf-4b8d25d01cf5
What is the average Selling, general and administrative? Success: 399.33 0.877s
<< (453 + 361 + 384) / 3 || [1198.0, 3, 399.3333333333333] || [453.0, 361.0, 384.0] || False >>
f7cac790-05ae-4a55-a41d-836a6b415f88
What is the percentage increase / (decrease) of Research, development and engineering from 2018 to 2019? Success: 88.06 1.252s
<< 126 / 67 - 1 || [126.0, 67.0, 88.05970149253731] || [126.0, 67.0] || True >>
65ec782c-691e-45df-b541-caecb85154ff
What was the change in Capital redemption reserve in 2019 from 2018? Success: 0.2 1.587s
<< 0.7-0.5 || [0.7, 0.5, 0.19999999999999996] || [0.7, 0.5] || True >>
94916f79-4b6d-487f-8fa2-39f81a085760
What was the percentage change in Capital redemption reserve in 2019 from 2018? Success: 40.0 1.220s
<< (0.7-0.5)/0.5 || [0.7, 0.5, 0.19999999999999996, 39.99999999999999] || [0.7, 0.5, 0.5] || True >>
bbe335ff-414f-48b3-8126-5a2c7c505de3
How much was the average operating income from 2015 to 2019? Success: 13237.4 1.665s
<<  (13,535+13,264+12,913+12,604+13,871) / 5  || [13237.4] || [13535.0, 13264.0, 12913.0, 12604.0, 13871.0] || False >>
ef274d2b-fbd6-4e9f-95f9-79b37827d91c
What was the total expenses for Oracle in 2018? failure: 26119.0 good answer:  35796  1.959s
<< 39,383-3,587  || [39383.0, 13264.0, 3587.0, 26119.0] || [39383.0, 3587.0] || True >>
191c3926-7356-4ab8-a8f9-41e7b7c8a492
What were the total Assets as reported? failure: 64509.0 good answer:  64509  0.975s
<< (19,373+22,626+22,510) || [64509.0] || [19373.0, 22626.0, 22510.0] || False >>
bd2d81eb-46fc-4e62-908d-aebfccf46246
What were the total Liabilities and Stockholders' Equity as reported? failure: 62740.0 good answer:  62740  0.759s
<< (24,264+38,476) || [62740.0] || [24264.0, 38476.0] || False >>
010df393-a62e-408d-888a-045a4e435e6a
What is the difference in amount between Deferred Revenue and Other non-current liabilities as reported? failure: 14212.0 good answer:  14212  0.004s
<< (38,476-24,264) || [24264.0, 38476.0, 14212.0] || [38476.0, 24264.0] || True >>
58adf6c4-41ae-4f3f-84cb-cf3469a80ce4
What was the percentage change in Total Other operating expenses between 2018 and 2019? Success: -67.6 1.268s
<< ($166.3-$513.3)/$513.3 || [166.3, 513.3, -67.60179232417688] || [166.3, 513.3, 513.3] || True >>
79f06004-f4fc-4e82-a9fe-3c389a2f81b6
What was the change in the statutory federal income tax rate from 2018 to 2019? Success: 0.0 1.646s
<< 21.0% - 21.0% || [21.0, 21.0, 0.0] || [21.0, 21.0] || True >>
a360cee9-ce60-4f29-988d-8c6c627bb51f
What was the average State and local income tax rate, net of federal tax benefits between 2017-2019? failure: 3.0 good answer:  3  0.637s
<< (3.7 + 3.7 + 1.6) / 3 || [] || [3.7, 3.7, 1.6] || False >>
5c8c999e-354f-4693-9b2d-29e3c03cb2af
What was the change in the preferred stock disposition from 2018 to 2019?[Error]
[Error]
 failure: [Error] good answer:  -9.9  1.420s
<< -9.9 - 0 || [] || [] || True >>
6cc73a99-0323-40d5-9d92-b285579b3482
What was the percentage change in gross profit between 2018 and 2019? Success: -13.66 1.696s
<< (315,652-365,607)/365,607 || [365607.0, 315652.0, -13.66] || [315652.0, 365607.0, 365607.0] || True >>
fa43e8cd-7fea-4738-85ee-f61ae8529f96
What was the change in the revenues from 2018 to 2019? Success: -21.7 1.215s
<< 1,073.3 - 1,095.0 || [1073.3, 1095.0, -21.700000000000045] || [1073.3, 1095.0] || True >>
*** Overall EM:  0.5675675675675675 / 20
2067daa1-9905-456b-bcbf-42bc66b47259
What is the average net income for 2018 and 2019? Success: 88.45 1.222s
<< (106.4 + 70.5) / 2 || [106.4, 70.5, 88.45] || [106.4, 70.5] || True >>
*** Overall EM:  0.5789473684210527 / 20
a1912c87-d68c-42ea-b0da-98908097d227
What was the change in closing cash? Success: 61.6 1.309s
<< 183.2-121.6 || [183.2, 121.6, 61.599999999999994] || [183.2, 121.6] || True >>
692ea65a-9a60-4210-bd75-d34231e2e113
What is the average total current tax expense for 2017 and 2018? [Error]
[Error]
 failure: [Error] good answer:  984  2.026s
<< (1,018+950)/2 || [] || [1018.0, 950.0] || False >>
7cba7400-af25-4f71-a49d-35d5eec31458
What is the average total current tax expense for 2018 and 2019?[Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType'
 failure: [Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType' good answer:  1040  1.573s
<< (1,062+1,018)/2 || [] || [1062.0, 1018.0] || False >>
94ef7822-a201-493e-b557-a640f4ea4d83
What is the change in the average total current tax expense between 2017-2018, and 2018-2019?[Error]name 'total_current' is not defined
[Error]name 'total_current' is not defined
 failure: [Error]name 'total_current' is not defined good answer:  56  3.713s
<< [(1,062+1,018)/2] - [(1,018+950)/2] || [] || [1062.0, 1018.0, 1018.0, 950.0] || False >>
bfce0375-cbd0-4e25-9b82-0424058918f1
What is the total number of nonvested shares as of December 31, 2019 and 2018? failure: 6148.0 good answer:  12122  1.706s
<< 6,148+5,974 || [5974.0, 6148.0] || [6148.0, 5974.0] || True >>
73693527-ed4b-4d07-941e-0e654095a43d
What was the employee termination costs as a proportion of total costs in 2018? failure: 0.95 good answer:  0.9500000000000001  3.103s
<< 53.0/55.5 || [2.0, 2.1, 0.9523809523809523] || [53.0, 55.5] || False >>
4a253bf4-b9fc-4ec3-b99b-d2744646a296
What was the change in Total (loan) in 2019 from 2018? Success: -56.5 1.278s
<< 828.8-885.3 || [828.8, 885.3] || [828.8, 885.3] || True >>
74183d5d-7633-43b5-bd7b-f0894fbe2299
What was the percentage change in Total (loan) in 2019 from 2018? Success: -6.38 1.569s
<< (828.8-885.3)/885.3 || [828.8, 885.3, -6.382017395233254] || [828.8, 885.3, 885.3] || True >>
1238d807-aa57-48a3-93b6-591873788625
What was the increase / (decrease) in the Statutory federal income tax (benefit) from 2018 to 2019? failure: -19411.0 good answer:  -19411  2.128s
<< 14,694 - 34,105 || [34105.0, 14694.0, -19411.0] || [14694.0, 34105.0] || True >>
ef9d4839-5277-4614-bb73-f902fd8a38b6
What was the average Tax exempt interest income? failure: -168.0 good answer:  -168  0.634s
<< - (197 + 101 + 206) / 3 || [-168.0] || [] || True >>
fec503e8-6f91-483e-856d-bb1278bd031f
What was the percentage change in the Domestic manufacturers deduction from 2017 to 2018? Success: -162.15 1.751s
<< -2,545 / 4,095 - 1 || [4095.0, -2545.0, -162.15] || [4095.0] || True >>
a3e21403-222e-4328-8f7d-9383d2d91fe9
What is the average dividend yield in 2017 and 2018? failure: 4.4 good answer:  4.35  0.776s
<< (4.1% + 4.6%)/2  || [4.3999999999999995] || [4.1, 4.6, 2.0] || False >>
a3637ae4-b286-44a5-a115-83867e4bb14e
What is the average dividend yield in 2018 and 2019? failure: 4.4 good answer:  4.55  0.627s
<< (4.6% + 4.5%)/2  || [4.3999999999999995] || [4.6, 4.5, 2.0] || False >>
d3f04ae4-ced9-446d-87b7-bb9d193e3603
What is the average expected volatility in 2017 and 2018? failure: 27.9 good answer:  27.9  1.121s
<< (27.1% + 28.7%)/2  || [27.1, 28.7, 27.9] || [27.1, 28.7, 2.0] || False >>
8b6a4479-3b77-4db7-a90c-8b1ca41a8997
What was the change in net debt from 2018 to 2019? Success: 59.39999999999998 1.118s
<< 295.2-235.8 || [295.2, 235.8, 59.39999999999998] || [295.2, 235.8] || True >>
7b2b17a9-6409-45fb-907f-270832305974
What was the percentage change in net debt from 2018 to 2019? Success: 25.19 1.214s
<< (295.2-235.8)/235.8 || [295.2, 235.8, 25.190839694656475] || [295.2, 235.8, 235.8] || True >>
3b5bb347-41c7-499a-b044-87b9a04b0833
What was the percentage change in Total Other in 2018 from 2017? Success: 15.85 1.867s
<< (95-82)/82 || [95.0, 82.0, 15.853658536585366] || [95.0, 82.0, 82.0] || True >>
*** Overall EM:  0.5454545454545454 / 30
0d0c77cf-d32c-4b0e-8da0-dcaa3f681f59
What is the percentage of Bell Wireless out of the Total BCE operating revenues in Q4 2019? Success: 39.47 1.486s
<< 2,493/6,316 || [39.47118429385687] || [2493.0, 6316.0] || False >>
259e18e8-4738-4f4d-b625-e352ca78a136
What is the increase / (decrease) in the recorded investment from 2018 to 2019? Success: -8736.0 1.295s
<< 22,446 - 31,182 || [31182.0, 22446.0, -8736.0] || [22446.0, 31182.0] || True >>
407d43ea-c405-4b88-95ae-d15b1f25fb25
What is the average Specific allowance for credit losses? Success: 198.5 1.131s
<< (177 + 220) / 2 || [177.0, 220.0, 198.5] || [177.0, 220.0] || True >>
681dcc0f-a32e-46ca-9785-1289a6aba802
What is the percentage increase / (decrease) in the Net financing receivables from 2018 to 2019? Success: -28.05 1.212s
<< 22,224 / 30,890 - 1 || [22224.0, 30890.0, -28.054386532858533] || [22224.0, 30890.0] || True >>
d2969c34-708e-4ab0-8e21-32c0b18c544c
What is the ratio of current deferred revenue to non-current deferred revenue as of end of period? Success: 1.3 1.239s
<< 4,483/3,444 || [4483.0, 3444.0, 1.301684088269454] || [4483.0, 3444.0] || True >>
59f13f19-4494-4c54-8e9a-1b499d50021a
What is the total price of shares that were exercised or canceled between 2016 and 2017? failure: -21850.124299999996 good answer:  981341.34  1.211s
<< (235,514*2.92)+(81,794*3.59)  || [-1870974.8699999999, -314037.56, -21850.124299999996] || [2.92, 3.59] || False >>
b382a11b-749b-425a-a77d-20e943e00f77
What is the proportion of granted shares between 2017 and 2018 over outstanding shares at September 30, 2017? failure: 0.25 good answer:  0.11  1.057s
<< 299,397/2,845,866  || [299397.0, 409368.0, 2845866.0, 708765.0, 0.24905072831960465] || [299397.0, 2845866.0] || True >>
741f8b2e-9312-4426-893d-69b99fab247b
What is the price of outstanding shares on September 30, 2019? failure: 7.0 good answer:  11808314  0.669s
<< 1,686,902*7.00  || [] || [1686902.0, 7.0] || False >>
cf89ffee-b551-4e34-9321-30325df32cc1
What was the change in the Amount recognized in other comprehensive (loss) income from 2017 to 2018? Success: -17.0 1.309s
<< -7 - 10 || [-7.0, 10.0, -17.0] || [10.0] || True >>
147f7c09-a627-4719-93ad-33661b5a4543
What was the change in Total interest expense, net presented in the consolidated statements of income in which the effects of cash flow hedges are recorded between 2017 and 2018? Success: -2.0 2.031s
<< 138-140 || [140.0, 138.0, -2.0] || [138.0, 140.0] || True >>
6a441650-9d8a-43a0-8906-bec97a73ca2c
What is the total special termination benefits charge in 2018 and 2019? Success: 21.0 1.185s
<< 6+15 || [21.0] || [6.0, 15.0] || False >>
eb1ecc18-e3d3-4dd6-a689-546998eb2784
What is the percentage change in interest cost in 2019 from 2018? Success: 11.22 1.599s
<< (436-392)/392 || [436.0, 392.0, 11.224489795918368] || [436.0, 392.0, 392.0] || True >>
8a21f821-eaf6-421a-8c67-795e7e2d1f61
What was the percentage change in Adjusted EBITDA between 2018 and 2019? Success: 16.36 1.722s
<< (108,307-93,081)/93,081 || [108307.0, 93081.0, 16.357795898196194] || [108307.0, 93081.0, 93081.0] || True >>
07ec204e-3922-4b5c-b1fd-9cb9311a53e5
What was the percentage change in the Total net deferred tax assets between 2018 and 2019? Success: -22.26 1.297s
<< (14,158-18,211)/18,211 || [18211.0, 14158.0, -4053.0, -22.25577947394432] || [14158.0, 18211.0, 18211.0] || True >>
f1034ee7-b182-48d5-bad8-1d9902500f57
What is the difference in the number of rights 'granted during the period' between 2018 and 2019? failure: -1226114.0 good answer:  1226114  0.004s
<< 5,691,731 - 4,465,617  || [5691731.0, 4465617.0, -1226114.0] || [5691731.0, 4465617.0] || True >>
*** Overall EM:  0.5857142857142857 / 40
545cb01f-9b10-4a1b-8a7c-e9e74e725b26
What is the average number of rights 'outstanding at end of period' for 2018 and 2019? Success: 12085176.0 1.222s
<< (13,477,758 + 10,692,594)/2  || [10692594.0, 13477758.0, 12085176.0] || [13477758.0, 10692594.0] || True >>
*** Overall EM:  0.5915492957746479 / 40
cc053817-3496-48b3-9bfc-83e9ba71bb57
What is the percentage increase in the number of rights 'outstanding at the start of period' from 2018 to 2019?  Success: 58.71 1.593s
<< (10,692,594 - 6,737,076)/6,737,076  || [6737076.0, 10692594.0, 58.71] || [10692594.0, 6737076.0, 6737076.0] || True >>
*** Overall EM:  0.5972222222222222 / 40
fda3b0cb-bc87-4cbc-bc8f-79604538a700
What is the average Legal reserve within Appropriation of earnings? Success: 835623.0 0.895s
<< (707,299+963,947) / 2 || [1671246.0, 2, 835623.0] || [707299.0, 963947.0] || False >>
8d8c9fb6-6316-4fad-881e-7cdb3cfa965a
What is the increase/ (decrease) in Legal reserve within Appropriation of earnings from 2018 to 2019? Success: 256648.0 1.056s
<< 963,947-707,299 || [707299.0, 963947.0, 256648.0] || [963947.0, 707299.0] || True >>
b4aabd48-5010-425f-be30-c63f1c648c85
What is the increase/ (decrease) in Cash dividends within Appropriation of earnings from 2018 to 2019? Success: 2849050.0 1.651s
<< 9,765,155-6,916,105 || [6916105.0, 9765155.0, 2849050.0] || [9765155.0, 6916105.0] || True >>
f12806ca-aa4c-4fe6-84fc-10cefca76a9e
What is the change in the operating revenue under continuing operations from 2018 to 2019? failure: -13.0 good answer:  -22772  1.207s
<< 154,159-176,931 || [] || [154159.0, 176931.0] || False >>
f36e5912-f63c-4837-a9ed-ddbe73e5148b
What is the percentage of the operating leases of more than 5 years in the total operating leases? failure: 12.02 good answer:  12.02  1.859s
<< 11,825/98,389 || [98389.0, 11825.0, 12.018619967679314] || [11825.0, 98389.0] || True >>
7ff6facd-1f7b-471c-9e38-5177c4eac9ba
What is the percentage of capital leases in the total liabilities? Success: 0.62 1.138s
<< 50,049/8,031,229 || [8031229.0, 50049.0, 0.6231798395986466] || [50049.0, 8031229.0] || True >>
d13b3204-0428-41af-8e4a-771dde352c50
What is the percentage of the purchase obligations of more than 5 years in the total purchase obligations? Success: 8.64 1.212s
<< 36,675/424,561 || [424561.0, 36675.0, 8.638334656268475] || [36675.0, 424561.0] || True >>
e1ae4755-8038-4862-9f2f-b4197f9f2159
What was the increase / (decrease) in the contractual obligation for operating leases from 2020 to 2021-2022? Success: 2968.0 1.470s
<< 7,111-4,143  || [4143.0, 7111.0, 2968.0] || [7111.0, 4143.0] || True >>
eb50d3aa-16da-4087-9ab2-10106ebd10e7
What is the average annual Operating leases contractual obligations for 2020-2024? failure: 4859.25 good answer:  2988  2.609s
<< (4,143+7,111+3,686)/5 || [4143.0, 7111.0, 3686.0, 4497.0, 19437.0, 4, 4859.25] || [4143.0, 7111.0, 3686.0] || True >>
61451090-3f7b-4fb1-b405-64a786d937d8
What was the increase / (decrease) in the asset retirement obligation from 2021-2022 to 2022-2023? Success: 100.0 1.808s
<< 250-150 || [150.0, 250.0, 100.0] || [250.0, 150.0] || True >>
56a014a9-5b9c-41e5-9523-ebbd3a01dd6d
What is the increase/ (decrease) in Statutory Audit, Certification, Audit of Individual and Consolidated Financial Statements from the period 2018 to 2019? Success: -451500.0 2.119s

0it [00:00, ?it/s]

cnt: 6
Base EM: 0.0
Base VM: 0.0
Fix EM: 0.8333333333333334
Fix VM: 0.8333333333333334
V29 global Error:
1774738924.0564117

0it [00:00, ?it/s]

b2786c1a-37de-4120-b03c-32bf5c81f157
What was the change in the amount for Appliances in 2019 from 2018? Success: -94.0 2.107s
<< 680-774 || [680.0, 774.0, -94.0] || [680.0, 774.0] || True >>
fe11f001-3bfe-4089-8108-412676f0a780
What was the percentage change in the amount for Appliances in 2019 from 2018? Success: -12.14 1.760s
<< (680-774)/774 || [680.0, 774.0, -12.144702842377262] || [680.0, 774.0, 774.0] || True >>
5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
What is the difference between the domestic and international discount rates as at September 30, 2019? failure: 2.1 good answer:  2.1  1.578s
<< 4.00 - 1.90  || [4.0, 1.9, 2.1] || [4.0, 1.9] || True >>
4dc8be43-d8d9-4b08-9ffd-9c19012361ce
What is the year on year percentage change in domestic discount rate between 2018 and 2019? failure: 6.67 good answer:  6.67  1.894s
<< (4.00 - 3.75)/3.75  || [3.75, 4.0, 6.666666666666667] || [4.0, 3.75, 3.75] || True >>
6c44a1a8-0785-43a0-90ab-7e21df2c57d9
What is the year on year percentage change in international expected return on plan assets between 2018 and 2019? failure: -8.11 good answer:  -8.11  1.585s
<< (3.40 - 3.70)/3.70  || [3.7, 3.4, -8.108108108108116] || [3.4, 3.7, 3.7] || True >>
a0414f81-8dc2-44b2-a441-2c9d9c805c4d
What is the 2019 average defined contribution schemes? Success: 172.0 0.004s
<< (166+178)/2 || [166.0, 178.0, 172.0] || [166.0, 178.0] || True >>
bf7abd62-d9cd-48d2-8826-1457684019a3
What is the 2019 average defined benefit schemes? Success: 50.5 0.002s
<< (57+44)/2 || [57.0, 44.0, 50.5] || [57.0, 44.0] || True >>
4d259081-6da6-44bd-8830-e4de0031744c
What is the difference between 2019 average defined contribution schemes and 2019 average defined benefit schemes? Success: 121.5 2.679s
<< [(166+178)/2] - [(57+44)/2] || [166.0, 57.0, 172.0, 50.5, 121.5] || [166.0, 178.0, 57.0, 44.0] || False >>
bed1fce2-69cb-4d1e-a34a-01950a1770bd
What is the percentage change in the operating loss carryforward from 2018 to 2019? Success: 26.82 1.587s
<< (73,260-57,768)/57,768 || [73260.0, 57768.0, 26.81761528874117] || [73260.0, 57768.0, 57768.0] || True >>
aea850af-68cb-4cc1-80b2-c9c2860b273e
What is the percentage change in the net deferred tax asset from 2018 to 2019? Success: 2.98 1.178s
<< (795-772)/772 || [795.0, 772.0, 0.029792746113989636] || [795.0, 772.0, 772.0] || True >>
ba6783f3-8207-419a-b407-3f688682caef
What is the ratio of IMFT’s total assets to total liabilities in 2019? Success: 2.93 1.476s
<< 2,664/909  || [2664.0, 909.0, 2.9306930693069306] || [2664.0, 909.0] || True >>
263d03ec-83d2-48df-8376-1a72167798f7
What is the proportion of IMFT’s property, plant, and equipment over total assets in 2018? failure: 87.31 good answer:  0.87  1.712s
<< 2,641/3,025  || [2641.0, 3025.0, 0.8730578512396694] || [2641.0, 3025.0] || True >>
78fc6d55-c20c-4f71-99fe-bc40a16e61d0
What is the change of IMFT’s total assets from 2018 to 2019? Success: -361.0 1.143s
<< 2,664 - 3,025  || [2664.0, 3025.0, -361.0] || [2664.0, 3025.0] || True >>
a4f782f1-de3b-47a3-87af-1cb33c112b39
What was the percentage change in Value added tax receivables, net, noncurrent in 2019 from 2018? Success: 14.07 1.291s
<< (592-519)/519 || [592.0, 519.0, 14.065510597302506] || [592.0, 519.0, 519.0] || True >>
dc5e217a-a7b3-4fc9-ac0f-13d328f26b20
What is the 2019 average free cash flow? Success: 4227.5 2.078s
<< (4,411+4,044)/2 || [4411.0, 4044.0, 4227.5] || [4411.0, 4044.0] || True >>
7cd3aedf-1291-4fea-bc9d-a25c65727b7b
What is the 2018 average free cash flow? Success: 3680.0 0.004s
<< (4,044+3,316)/2 || [4044.0, 3316.0, 3680.0] || [4044.0, 3316.0] || True >>
22e20f25-669a-46b9-8779-2768ba391955
What is the change between 2018 and 2019 average free cash flow? failure: 4227.5 good answer:  547.5  1.751s
<< [(4,411+4,044)/2] -[(4,044+3,316)/2] || [4411.0, 4044.0, 4227.5] || [4411.0, 4044.0, 4044.0, 3316.0] || False >>
a983501d-2eec-486d-9661-e520c7c8af5e
What was the average difference between EBITDA and underlying EBITDA for both FYs? failure: -2349.0 good answer:  3728  2.860s
<< ((85,123 - 79,046) + (63,954 - 62,575)) / 2  || [79046.0, 63954.0, 85123.0, 62575.0, -6077.0, 1379.0, -2349.0] || [85123.0, 79046.0, 63954.0, 62575.0] || True >>
64c902c6-f426-4432-84b3-c10b3065716f
What was the difference in net profit between both FYs? Success: -16458.0 1.460s
<< -9,819 - 6,639  || [-9819.0, 6639.0, -16458.0] || [6639.0] || True >>
91812b92-5e94-414f-a447-4622aa3c2d10
What was the average dividend yield for the 3 years from 2017 to 2019? failure: 1.57 good answer:  1.57  0.712s
<< (1.7%+1.5%+1.5%)/3 || [1.5666666666666667] || [1.7, 1.5, 1.5] || False >>
*** Overall EM:  0.85 / 10
29b63db7-4925-4629-b108-49bbb27fb565
What was the average risk-free interest rate over the 3 year period from 2017 to 2019? failure: 1.9 good answer:  1.9  1.578s
<< (2.7%+2.0%+1.0%)/3 || [1.0, 2.0, 2.7, 1.9000000000000001] || [2.7, 2.0, 1.0] || True >>
*** Overall EM:  0.8571428571428571 / 10
6100c476-160a-4f1e-bfc1-a16f4cc18b52
What was the increase / (decrease) in the cost from 2018 to 2019? Success: 18.0 1.302s
<< 100 - 82 || [82.0, 100.0, 18.0] || [100.0, 82.0] || True >>
a81f1322-e74f-4e3c-a6cf-4b8d25d01cf5
What is the average Selling, general and administrative? failure: 407.0 good answer:  399.33  1.026s
<< (453 + 361 + 384) / 3 || [407.0] || [453.0, 361.0, 384.0] || False >>
f7cac790-05ae-4a55-a41d-836a6b415f88
What is the percentage increase / (decrease) of Research, development and engineering from 2018 to 2019? Success: 88.06 1.702s
<< 126 / 67 - 1 || [67.0, 126.0, 88.05970149253731] || [126.0, 67.0] || True >>
65ec782c-691e-45df-b541-caecb85154ff
What was the change in Capital redemption reserve in 2019 from 2018? Success: 0.2 1.417s
<< 0.7-0.5 || [0.7, 0.5, 0.19999999999999996] || [0.7, 0.5] || True >>
94916f79-4b6d-487f-8fa2-39f81a085760
What was the percentage change in Capital redemption reserve in 2019 from 2018? Success: 40.0 1.189s
<< (0.7-0.5)/0.5 || [0.7, 0.5, 39.99999999999999] || [0.7, 0.5, 0.5] || True >>
bbe335ff-414f-48b3-8126-5a2c7c505de3
How much was the average operating income from 2015 to 2019? Success: 13237.4 1.658s
<<  (13,535+13,264+12,913+12,604+13,871) / 5  || [13237.4] || [13535.0, 13264.0, 12913.0, 12604.0, 13871.0] || False >>
ef274d2b-fbd6-4e9f-95f9-79b37827d91c
What was the total expenses for Oracle in 2018? failure: -108148.0 good answer:  35796  3.319s
<< 39,383-3,587  || [39383.0, 13264.0, 57035.0, 137851.0, 60619.0, -108148.0] || [39383.0, 3587.0] || False >>
191c3926-7356-4ab8-a8f9-41e7b7c8a492
What were the total Assets as reported? failure: 64509.0 good answer:  64509  1.780s
<< (19,373+22,626+22,510) || [19373.0, 22626.0, 22510.0, 64509.0] || [19373.0, 22626.0, 22510.0] || True >>
bd2d81eb-46fc-4e62-908d-aebfccf46246
What were the total Liabilities and Stockholders' Equity as reported? failure: 62740.0 good answer:  62740  0.797s
<< (24,264+38,476) || [62740.0] || [24264.0, 38476.0] || False >>
010df393-a62e-408d-888a-045a4e435e6a
What is the difference in amount between Deferred Revenue and Other non-current liabilities as reported? failure: -14212.0 good answer:  14212  1.141s
<< (38,476-24,264) || [24264.0, 38476.0, -14212.0] || [38476.0, 24264.0] || True >>
58adf6c4-41ae-4f3f-84cb-cf3469a80ce4
What was the percentage change in Total Other operating expenses between 2018 and 2019? Success: -67.6 1.606s
<< ($166.3-$513.3)/$513.3 || [513.3, 166.3, -67.60179232417688] || [166.3, 513.3, 513.3] || True >>
79f06004-f4fc-4e82-a9fe-3c389a2f81b6
What was the change in the statutory federal income tax rate from 2018 to 2019? Success: 0.0 1.651s
<< 21.0% - 21.0% || [21.0, 21.0, 0.0] || [21.0, 21.0] || True >>
a360cee9-ce60-4f29-988d-8c6c627bb51f
What was the average State and local income tax rate, net of federal tax benefits between 2017-2019? failure: 3.0 good answer:  3  0.771s
<< (3.7 + 3.7 + 1.6) / 3 || [3.0] || [3.7, 3.7, 1.6] || False >>
5c8c999e-354f-4693-9b2d-29e3c03cb2af
What was the change in the preferred stock disposition from 2018 to 2019?[Error]
[Error]
 failure: [Error] good answer:  -9.9  1.320s
<< -9.9 - 0 || [] || [] || True >>
6cc73a99-0323-40d5-9d92-b285579b3482
What was the percentage change in gross profit between 2018 and 2019? Success: -13.66 1.621s
<< (315,652-365,607)/365,607 || [365607.0, 315652.0, -13.663578651393435] || [315652.0, 365607.0, 365607.0] || True >>
fa43e8cd-7fea-4738-85ee-f61ae8529f96
What was the change in the revenues from 2018 to 2019? Success: -21.7 1.241s
<< 1,073.3 - 1,095.0 || [1073.3, 1095.0, -21.700000000000045] || [1073.3, 1095.0] || True >>
*** Overall EM:  0.7297297297297297 / 20
2067daa1-9905-456b-bcbf-42bc66b47259
What is the average net income for 2018 and 2019? Success: 88.45 1.223s
<< (106.4 + 70.5) / 2 || [106.4, 70.5, 88.45] || [106.4, 70.5] || True >>
*** Overall EM:  0.7368421052631579 / 20
a1912c87-d68c-42ea-b0da-98908097d227
What was the change in closing cash? Success: 61.6 1.638s
<< 183.2-121.6 || [183.2, 121.6, 61.599999999999994] || [183.2, 121.6] || True >>
692ea65a-9a60-4210-bd75-d34231e2e113
What is the average total current tax expense for 2017 and 2018? [Error]
[Error]
 failure: [Error] good answer:  984  2.045s
<< (1,018+950)/2 || [] || [1018.0, 950.0] || False >>
7cba7400-af25-4f71-a49d-35d5eec31458
What is the average total current tax expense for 2018 and 2019?[Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType'
 failure: [Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType' good answer:  1040  1.565s
<< (1,062+1,018)/2 || [] || [1062.0, 1018.0] || False >>
94ef7822-a201-493e-b557-a640f4ea4d83
What is the change in the average total current tax expense between 2017-2018, and 2018-2019?[Error]name 'current_year2_2' is not defined
[Error]name 'current_year2_2' is not defined
 failure: [Error]name 'current_year2_2' is not defined good answer:  56  3.723s
<< [(1,062+1,018)/2] - [(1,018+950)/2] || [] || [1062.0, 1018.0, 1018.0, 950.0] || False >>
bfce0375-cbd0-4e25-9b82-0424058918f1
What is the total number of nonvested shares as of December 31, 2019 and 2018? Success: 12122.0 1.204s
<< 6,148+5,974 || [5974.0, 6148.0, 12122.0] || [6148.0, 5974.0] || True >>
73693527-ed4b-4d07-941e-0e654095a43d
What was the employee termination costs as a proportion of total costs in 2018? failure: 0.04 good answer:  0.9500000000000001  2.577s
<< 53.0/55.5 || [2.0, 55.5, 0.036036036036036036] || [53.0, 55.5] || False >>
4a253bf4-b9fc-4ec3-b99b-d2744646a296
What was the change in Total (loan) in 2019 from 2018? Success: -56.5 1.311s
<< 828.8-885.3 || [828.8, 885.3, -56.5] || [828.8, 885.3] || True >>
74183d5d-7633-43b5-bd7b-f0894fbe2299
What was the percentage change in Total (loan) in 2019 from 2018? Success: -6.38 1.601s
<< (828.8-885.3)/885.3 || [828.8, 885.3, -6.382017395233254] || [828.8, 885.3, 885.3] || True >>
1238d807-aa57-48a3-93b6-591873788625
What was the increase / (decrease) in the Statutory federal income tax (benefit) from 2018 to 2019? failure: -19411.0 good answer:  -19411  2.084s
<< 14,694 - 34,105 || [34105.0, 14694.0, -19411.0] || [14694.0, 34105.0] || True >>
ef9d4839-5277-4614-bb73-f902fd8a38b6
What was the average Tax exempt interest income? failure: -168.0 good answer:  -168  0.959s
<< - (197 + 101 + 206) / 3 || [-168.0] || [] || True >>
fec503e8-6f91-483e-856d-bb1278bd031f
What was the percentage change in the Domestic manufacturers deduction from 2017 to 2018? Success: -162.15 1.773s
<< -2,545 / 4,095 - 1 || [4095.0, -2545.0, -162.15] || [4095.0] || True >>
a3e21403-222e-4328-8f7d-9383d2d91fe9
What is the average dividend yield in 2017 and 2018? failure: 4.3999999999999995 good answer:  4.35  0.676s
<< (4.1% + 4.6%)/2  || [] || [4.1, 4.6, 2.0] || False >>
a3637ae4-b286-44a5-a115-83867e4bb14e
What is the average dividend yield in 2018 and 2019? failure: 4.4 good answer:  4.55  0.634s
<< (4.6% + 4.5%)/2  || [4.3999999999999995] || [4.6, 4.5, 2.0] || False >>
d3f04ae4-ced9-446d-87b7-bb9d193e3603
What is the average expected volatility in 2017 and 2018? failure: 27.9 good answer:  27.9  1.127s
<< (27.1% + 28.7%)/2  || [27.1, 28.7, 27.9] || [27.1, 28.7, 2.0] || False >>
8b6a4479-3b77-4db7-a90c-8b1ca41a8997
What was the change in net debt from 2018 to 2019? Success: 59.4 1.204s
<< 295.2-235.8 || [295.2, 235.8, 59.39999999999998] || [295.2, 235.8] || True >>
7b2b17a9-6409-45fb-907f-270832305974
What was the percentage change in net debt from 2018 to 2019? Success: 25.19 1.250s
<< (295.2-235.8)/235.8 || [295.2, 235.8, 25.190839694656475] || [295.2, 235.8, 235.8] || True >>
3b5bb347-41c7-499a-b044-87b9a04b0833
What was the percentage change in Total Other in 2018 from 2017? Success: 15.85 2.212s
<< (95-82)/82 || [95.0, 82.0, 15.85] || [95.0, 82.0, 82.0] || True >>
*** Overall EM:  0.6727272727272727 / 30
0d0c77cf-d32c-4b0e-8da0-dcaa3f681f59
What is the percentage of Bell Wireless out of the Total BCE operating revenues in Q4 2019? failure: 39.47 good answer:  39.47  1.497s
<< 2,493/6,316 || [6316.0, 2493.0, 39.47118429385687] || [2493.0, 6316.0] || True >>
259e18e8-4738-4f4d-b625-e352ca78a136
What is the increase / (decrease) in the recorded investment from 2018 to 2019? Success: -8736.0 1.258s
<< 22,446 - 31,182 || [31182.0, 22446.0, -8736.0] || [22446.0, 31182.0] || True >>
407d43ea-c405-4b88-95ae-d15b1f25fb25
What is the average Specific allowance for credit losses? Success: 198.5 1.158s
<< (177 + 220) / 2 || [177.0, 220.0, 198.5] || [177.0, 220.0] || True >>
681dcc0f-a32e-46ca-9785-1289a6aba802
What is the percentage increase / (decrease) in the Net financing receivables from 2018 to 2019? Success: -28.05 1.525s
<< 22,224 / 30,890 - 1 || [30890.0, 22224.0, -28.054386532858533] || [22224.0, 30890.0] || True >>
d2969c34-708e-4ab0-8e21-32c0b18c544c
What is the ratio of current deferred revenue to non-current deferred revenue as of end of period? failure: 1.301684088269454 good answer:  1.3  1.173s
<< 4,483/3,444 || [4483.0, 3444.0] || [4483.0, 3444.0] || True >>
59f13f19-4494-4c54-8e9a-1b499d50021a
What is the total price of shares that were exercised or canceled between 2016 and 2017? failure: 0.0 good answer:  981341.34  1.244s
<< (235,514*2.92)+(81,794*3.59)  || [0.0] || [2.92, 3.59] || False >>
b382a11b-749b-425a-a77d-20e943e00f77
What is the proportion of granted shares between 2017 and 2018 over outstanding shares at September 30, 2017? failure: 0.1 good answer:  0.11  2.213s
<< 299,397/2,845,866  || [2845866.0, 147800.0, 147800.0, 295600.0, 0.10386996436234172] || [299397.0, 2845866.0] || False >>
741f8b2e-9312-4426-893d-69b99fab247b
What is the price of outstanding shares on September 30, 2019? failure: 7.0 good answer:  11808314  0.672s
<< 1,686,902*7.00  || [] || [1686902.0, 7.0] || False >>
cf89ffee-b551-4e34-9321-30325df32cc1
What was the change in the Amount recognized in other comprehensive (loss) income from 2017 to 2018? Success: -17.0 1.794s
<< -7 - 10 || [10.0, -7.0, -17.0] || [10.0] || True >>
147f7c09-a627-4719-93ad-33661b5a4543
What was the change in Total interest expense, net presented in the consolidated statements of income in which the effects of cash flow hedges are recorded between 2017 and 2018? Success: -2.0 1.729s
<< 138-140 || [140.0, 138.0, -2.0] || [138.0, 140.0] || True >>
6a441650-9d8a-43a0-8906-bec97a73ca2c
What is the total special termination benefits charge in 2018 and 2019? Success: 21.0 1.277s
<< 6+15 || [21.0] || [6.0, 15.0] || False >>
eb1ecc18-e3d3-4dd6-a689-546998eb2784
What is the percentage change in interest cost in 2019 from 2018? Success: 11.22 1.600s
<< (436-392)/392 || [436.0, 392.0, 11.224489795918368] || [436.0, 392.0, 392.0] || True >>
8a21f821-eaf6-421a-8c67-795e7e2d1f61
What was the percentage change in Adjusted EBITDA between 2018 and 2019? Success: 16.36 2.098s
<< (108,307-93,081)/93,081 || [108307.0, 93081.0, 16.36] || [108307.0, 93081.0, 93081.0] || True >>
07ec204e-3922-4b5c-b1fd-9cb9311a53e5
What was the percentage change in the Total net deferred tax assets between 2018 and 2019? Success: -22.26 1.476s
<< (14,158-18,211)/18,211 || [18211.0, 14158.0, -22.25577947394432] || [14158.0, 18211.0, 18211.0] || True >>
f1034ee7-b182-48d5-bad8-1d9902500f57
What is the difference in the number of rights 'granted during the period' between 2018 and 2019? failure: -1226114.0 good answer:  1226114  1.393s
<< 5,691,731 - 4,465,617  || [5691731.0, 4465617.0, -1226114.0] || [5691731.0, 4465617.0] || True >>
*** Overall EM:  0.6714285714285714 / 40
545cb01f-9b10-4a1b-8a7c-e9e74e725b26
What is the average number of rights 'outstanding at end of period' for 2018 and 2019? Success: 12085176.0 1.462s
<< (13,477,758 + 10,692,594)/2  || [10692594.0, 13477758.0, 12085176.0] || [13477758.0, 10692594.0] || True >>
*** Overall EM:  0.676056338028169 / 40
cc053817-3496-48b3-9bfc-83e9ba71bb57
What is the percentage increase in the number of rights 'outstanding at the start of period' from 2018 to 2019?  Success: 58.71 1.549s
<< (10,692,594 - 6,737,076)/6,737,076  || [6737076.0, 10692594.0, 58.712681881575925] || [10692594.0, 6737076.0, 6737076.0] || True >>
*** Overall EM:  0.6805555555555556 / 40
fda3b0cb-bc87-4cbc-bc8f-79604538a700
What is the average Legal reserve within Appropriation of earnings? Success: 835623.0 0.890s
<< (707,299+963,947) / 2 || [1671246.0, 2, 835623.0] || [707299.0, 963947.0] || False >>
8d8c9fb6-6316-4fad-881e-7cdb3cfa965a
What is the increase/ (decrease) in Legal reserve within Appropriation of earnings from 2018 to 2019? Success: 256648.0 1.075s
<< 963,947-707,299 || [707299.0, 963947.0, 256648.0] || [963947.0, 707299.0] || True >>
b4aabd48-5010-425f-be30-c63f1c648c85
What is the increase/ (decrease) in Cash dividends within Appropriation of earnings from 2018 to 2019?[Error]
[Error]
 failure: [Error] good answer:  2849050  1.690s
<< 9,765,155-6,916,105 || [] || [9765155.0, 6916105.0] || False >>
f12806ca-aa4c-4fe6-84fc-10cefca76a9e
What is the change in the operating revenue under continuing operations from 2018 to 2019? Success: -22772.0 2.425s
<< 154,159-176,931 || [154159.0, 176931.0, -22772.0] || [154159.0, 176931.0] || True >>
f36e5912-f63c-4837-a9ed-ddbe73e5148b
What is the percentage of the operating leases of more than 5 years in the total operating leases? Success: 12.02 1.527s
<< 11,825/98,389 || [98389.0, 11825.0, 12.018619967679314] || [11825.0, 98389.0] || True >>
7ff6facd-1f7b-471c-9e38-5177c4eac9ba
What is the percentage of capital leases in the total liabilities? failure: 1.25 good answer:  0.62  0.916s
<< 50,049/8,031,229 || [100098.0, 8031229.0, 1.2463596791972933] || [50049.0, 8031229.0] || False >>
d13b3204-0428-41af-8e4a-771dde352c50
What is the percentage of the purchase obligations of more than 5 years in the total purchase obligations? Success: 8.64 1.199s
<< 36,675/424,561 || [424561.0, 36675.0, 8.638334656268475] || [36675.0, 424561.0] || True >>
e1ae4755-8038-4862-9f2f-b4197f9f2159
What was the increase / (decrease) in the contractual obligation for operating leases from 2020 to 2021-2022? failure: 2.97 good answer:  2968  1.769s
<< 7,111-4,143  || [4143.0, 7111.0] || [7111.0, 4143.0] || True >>
eb50d3aa-16da-4087-9ab2-10106ebd10e7
What is the average annual Operating leases contractual obligations for 2020-2024? failure: 4859.25 good answer:  2988  2.573s
<< (4,143+7,111+3,686)/5 || [4143.0, 7111.0, 3686.0, 4497.0, 19437.0, 4859.25] || [4143.0, 7111.0, 3686.0] || True >>
61451090-3f7b-4fb1-b405-64a786d937d8
What was the increase / (decrease) in the asset retirement obligation from 2021-2022 to 2022-2023? Success: 100.0 1.652s
<< 250-150 || [150.0, 250.0, 100.0] || [250.0, 150.0] || True >>
56a014a9-5b9c-41e5-9523-ebbd3a01dd6d
What is the increase/ (decrease) in Statutory Audit, Certification, Audit of Individual and Consolidated Financial Statements from the period 2018 to 2019? Success: -451500.0 2.041s
<< 4,105,000-4,556,500 || [4105000.0, 4556500.0, -451500.0] || [4105000.0, 4556500.0] || True >>
2af4c7cf-79a2-4bdf-81b8-dbaff5081bc3

0it [00:00, ?it/s]

cnt: 7
Base EM: 0.0
Base VM: 0.0
Fix EM: 0.5714285714285714
Fix VM: 0.7142857142857143
V31 global Error:
1774739697.4482994

0it [00:00, ?it/s]

b2786c1a-37de-4120-b03c-32bf5c81f157
What was the change in the amount for Appliances in 2019 from 2018? Success: -94.0 1.770s
<< 680-774 || [680.0, 774.0, -94.0] || [680.0, 774.0] || True >>
fe11f001-3bfe-4089-8108-412676f0a780
What was the percentage change in the amount for Appliances in 2019 from 2018? Success: -12.14 1.721s
<< (680-774)/774 || [680.0, 774.0, -12.144702842377262] || [680.0, 774.0, 774.0] || True >>
5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
What is the difference between the domestic and international discount rates as at September 30, 2019? failure: 2.1 good answer:  2.1  1.594s
<< 4.00 - 1.90  || [4.0, 1.9, 2.1] || [4.0, 1.9] || True >>
4dc8be43-d8d9-4b08-9ffd-9c19012361ce
What is the year on year percentage change in domestic discount rate between 2018 and 2019? failure: 6.67 good answer:  6.67  1.889s
<< (4.00 - 3.75)/3.75  || [3.75, 4.0, 6.666666666666667] || [4.0, 3.75, 3.75] || True >>
6c44a1a8-0785-43a0-90ab-7e21df2c57d9
What is the year on year percentage change in international expected return on plan assets between 2018 and 2019? failure: -8.11 good answer:  -8.11  1.970s
<< (3.40 - 3.70)/3.70  || [3.7, 3.4, -8.11] || [3.4, 3.7, 3.7] || True >>
a0414f81-8dc2-44b2-a441-2c9d9c805c4d
What is the 2019 average defined contribution schemes? Success: 172.0 1.239s
<< (166+178)/2 || [166.0, 178.0, 172.0] || [166.0, 178.0] || True >>
bf7abd62-d9cd-48d2-8826-1457684019a3
What is the 2019 average defined benefit schemes? Success: 50.5 1.413s
<< (57+44)/2 || [57.0, 44.0, 50.5] || [57.0, 44.0] || True >>
4d259081-6da6-44bd-8830-e4de0031744c
What is the difference between 2019 average defined contribution schemes and 2019 average defined benefit schemes? failure: 109.0 good answer:  121.5  1.888s
<< [(166+178)/2] - [(57+44)/2] || [166.0, 57.0, 109.0] || [166.0, 178.0, 57.0, 44.0] || False >>
bed1fce2-69cb-4d1e-a34a-01950a1770bd
What is the percentage change in the operating loss carryforward from 2018 to 2019? Success: 26.82 1.599s
<< (73,260-57,768)/57,768 || [73260.0, 57768.0, 26.81761528874117] || [73260.0, 57768.0, 57768.0] || True >>
aea850af-68cb-4cc1-80b2-c9c2860b273e
What is the percentage change in the net deferred tax asset from 2018 to 2019? Success: 2.98 1.305s
<< (795-772)/772 || [795.0, 772.0, 2.9792746113989637] || [795.0, 772.0, 772.0] || True >>
ba6783f3-8207-419a-b407-3f688682caef
What is the ratio of IMFT’s total assets to total liabilities in 2019? Success: 2.93 1.474s
<< 2,664/909  || [2664.0, 909.0, 2.9306930693069306] || [2664.0, 909.0] || True >>
263d03ec-83d2-48df-8376-1a72167798f7
What is the proportion of IMFT’s property, plant, and equipment over total assets in 2018? failure: 0.87 good answer:  0.87  1.233s
<< 2,641/3,025  || [3025.0, 2641.0, 0.8730578512396694] || [2641.0, 3025.0] || True >>
78fc6d55-c20c-4f71-99fe-bc40a16e61d0
What is the change of IMFT’s total assets from 2018 to 2019? Success: -361.0 1.136s
<< 2,664 - 3,025  || [2664.0, 3025.0, -361.0] || [2664.0, 3025.0] || True >>
a4f782f1-de3b-47a3-87af-1cb33c112b39
What was the percentage change in Value added tax receivables, net, noncurrent in 2019 from 2018? Success: 14.07 1.134s
<< (592-519)/519 || [592.0, 519.0, 14.065510597302506] || [592.0, 519.0, 519.0] || True >>
dc5e217a-a7b3-4fc9-ac0f-13d328f26b20
What is the 2019 average free cash flow? Success: 4227.5 1.708s
<< (4,411+4,044)/2 || [4411.0, 4044.0, 4227.5] || [4411.0, 4044.0] || True >>
7cd3aedf-1291-4fea-bc9d-a25c65727b7b
What is the 2018 average free cash flow? failure: 4227.5 good answer:  3680  1.312s
<< (4,044+3,316)/2 || [4411.0, 4044.0, 4227.5] || [4044.0, 3316.0] || False >>
22e20f25-669a-46b9-8779-2768ba391955
What is the change between 2018 and 2019 average free cash flow? failure: 4227.5 good answer:  547.5  1.755s
<< [(4,411+4,044)/2] -[(4,044+3,316)/2] || [4411.0, 4044.0, 4227.5] || [4411.0, 4044.0, 4044.0, 3316.0] || False >>
a983501d-2eec-486d-9661-e520c7c8af5e
What was the average difference between EBITDA and underlying EBITDA for both FYs? failure: -2349.0 good answer:  3728  2.868s
<< ((85,123 - 79,046) + (63,954 - 62,575)) / 2  || [79046.0, 63954.0, 85123.0, 62575.0, -6077.0, 1379.0, -2349.0] || [85123.0, 79046.0, 63954.0, 62575.0] || True >>
64c902c6-f426-4432-84b3-c10b3065716f
What was the difference in net profit between both FYs? Success: -16458.0 1.466s
<< -9,819 - 6,639  || [-9819.0, 6639.0, -16458.0] || [6639.0] || True >>
91812b92-5e94-414f-a447-4622aa3c2d10
What was the average dividend yield for the 3 years from 2017 to 2019? failure: 1.57 good answer:  1.57  0.720s
<< (1.7%+1.5%+1.5%)/3 || [1.5666666666666667] || [1.7, 1.5, 1.5] || False >>
*** Overall EM:  0.75 / 10
29b63db7-4925-4629-b108-49bbb27fb565
What was the average risk-free interest rate over the 3 year period from 2017 to 2019? failure: 1.9000000000000001 good answer:  1.9  0.523s
<< (2.7%+2.0%+1.0%)/3 || [] || [2.7, 2.0, 1.0] || False >>
*** Overall EM:  0.7619047619047619 / 10
6100c476-160a-4f1e-bfc1-a16f4cc18b52
What was the increase / (decrease) in the cost from 2018 to 2019? Success: 18.0 1.350s
<< 100 - 82 || [82.0, 100.0, 18.0] || [100.0, 82.0] || True >>
a81f1322-e74f-4e3c-a6cf-4b8d25d01cf5
What is the average Selling, general and administrative? Success: 399.33 0.004s
<< (453 + 361 + 384) / 3 || [1198.0, 3, 399.3333333333333] || [453.0, 361.0, 384.0] || False >>
f7cac790-05ae-4a55-a41d-836a6b415f88
What is the percentage increase / (decrease) of Research, development and engineering from 2018 to 2019? Success: 88.06 1.290s
<< 126 / 67 - 1 || [67.0, 126.0, 88.05970149253731] || [126.0, 67.0] || True >>
65ec782c-691e-45df-b541-caecb85154ff
What was the change in Capital redemption reserve in 2019 from 2018? Success: 0.2 1.419s
<< 0.7-0.5 || [0.7, 0.5, 0.19999999999999996] || [0.7, 0.5] || True >>
94916f79-4b6d-487f-8fa2-39f81a085760
What was the percentage change in Capital redemption reserve in 2019 from 2018? Success: 40.0 1.179s
<< (0.7-0.5)/0.5 || [0.7, 0.5, 39.99999999999999] || [0.7, 0.5, 0.5] || True >>
bbe335ff-414f-48b3-8126-5a2c7c505de3
How much was the average operating income from 2015 to 2019? Success: 13237.4 1.514s
<<  (13,535+13,264+12,913+12,604+13,871) / 5  || [] || [13535.0, 13264.0, 12913.0, 12604.0, 13871.0] || False >>
ef274d2b-fbd6-4e9f-95f9-79b37827d91c
What was the total expenses for Oracle in 2018? failure: 38587.5 good answer:  35796  1.557s
<< 39,383-3,587  || [39383.0, 37792.0, 38587.5] || [39383.0, 3587.0] || False >>
191c3926-7356-4ab8-a8f9-41e7b7c8a492
What were the total Assets as reported? failure: 22510.0 good answer:  64509  1.030s
<< (19,373+22,626+22,510) || [22510.0] || [19373.0, 22626.0, 22510.0] || False >>
bd2d81eb-46fc-4e62-908d-aebfccf46246
What were the total Liabilities and Stockholders' Equity as reported? failure: 62740.0 good answer:  62740  0.814s
<< (24,264+38,476) || [62740.0] || [24264.0, 38476.0] || False >>
010df393-a62e-408d-888a-045a4e435e6a
What is the difference in amount between Deferred Revenue and Other non-current liabilities as reported? failure: -14212.0 good answer:  14212  1.069s
<< (38,476-24,264) || [24264.0, 38476.0] || [38476.0, 24264.0] || True >>
58adf6c4-41ae-4f3f-84cb-cf3469a80ce4
What was the percentage change in Total Other operating expenses between 2018 and 2019? Success: -67.6 1.295s
<< ($166.3-$513.3)/$513.3 || [166.3, 513.3, -67.60179232417688] || [166.3, 513.3, 513.3] || True >>
79f06004-f4fc-4e82-a9fe-3c389a2f81b6
What was the change in the statutory federal income tax rate from 2018 to 2019? Success: 0.0 1.659s
<< 21.0% - 21.0% || [21.0, 21.0, 0.0] || [21.0, 21.0] || True >>
a360cee9-ce60-4f29-988d-8c6c627bb51f
What was the average State and local income tax rate, net of federal tax benefits between 2017-2019? failure: 3.0 good answer:  3  0.776s
<< (3.7 + 3.7 + 1.6) / 3 || [3.0] || [3.7, 3.7, 1.6] || False >>
5c8c999e-354f-4693-9b2d-29e3c03cb2af
What was the change in the preferred stock disposition from 2018 to 2019?[Error]
[Error]
 failure: [Error] good answer:  -9.9  1.330s
<< -9.9 - 0 || [] || [] || True >>
6cc73a99-0323-40d5-9d92-b285579b3482
What was the percentage change in gross profit between 2018 and 2019? Success: -13.66 1.715s
<< (315,652-365,607)/365,607 || [365607.0, 315652.0, -13.66] || [315652.0, 365607.0, 365607.0] || True >>
fa43e8cd-7fea-4738-85ee-f61ae8529f96
What was the change in the revenues from 2018 to 2019? Success: -21.7 1.244s
<< 1,073.3 - 1,095.0 || [1073.3, 1095.0, -21.700000000000045] || [1073.3, 1095.0] || True >>
*** Overall EM:  0.7027027027027027 / 20
2067daa1-9905-456b-bcbf-42bc66b47259
What is the average net income for 2018 and 2019? Success: 88.45 1.219s
<< (106.4 + 70.5) / 2 || [106.4, 70.5, 88.45] || [106.4, 70.5] || True >>
*** Overall EM:  0.7105263157894737 / 20
a1912c87-d68c-42ea-b0da-98908097d227
What was the change in closing cash? Success: 61.6 1.640s
<< 183.2-121.6 || [183.2, 121.6, 61.599999999999994] || [183.2, 121.6] || True >>
692ea65a-9a60-4210-bd75-d34231e2e113
What is the average total current tax expense for 2017 and 2018?  failure: 0.0 good answer:  984  2.106s
<< (1,018+950)/2 || [0, 0, 0.0] || [1018.0, 950.0] || False >>
7cba7400-af25-4f71-a49d-35d5eec31458
What is the average total current tax expense for 2018 and 2019?[Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType'
 failure: [Error]unsupported operand type(s) for +: 'NoneType' and 'NoneType' good answer:  1040  1.572s
<< (1,062+1,018)/2 || [] || [1062.0, 1018.0] || False >>
94ef7822-a201-493e-b557-a640f4ea4d83
What is the change in the average total current tax expense between 2017-2018, and 2018-2019?[Error]EOL while scanning string literal (<string>, line 11)
[Error]EOL while scanning string literal (<string>, line 11)
 failure: [Error]EOL while scanning string literal (<string>, line 11) good answer:  56  3.734s
<< [(1,062+1,018)/2] - [(1,018+950)/2] || [] || [1062.0, 1018.0, 1018.0, 950.0] || False >>
bfce0375-cbd0-4e25-9b82-0424058918f1
What is the total number of nonvested shares as of December 31, 2019 and 2018? Success: 12122.0 1.215s
<< 6,148+5,974 || [5974.0, 6148.0, 12122.0] || [6148.0, 5974.0] || True >>
73693527-ed4b-4d07-941e-0e654095a43d
What was the employee termination costs as a proportion of total costs in 2018? failure: 0.04 good answer:  0.9500000000000001  2.576s
<< 53.0/55.5 || [2.0, 55.5, 0.036036036036036036] || [53.0, 55.5] || False >>
4a253bf4-b9fc-4ec3-b99b-d2744646a296
What was the change in Total (loan) in 2019 from 2018? Success: -56.5 1.293s
<< 828.8-885.3 || [828.8, 885.3] || [828.8, 885.3] || True >>
74183d5d-7633-43b5-bd7b-f0894fbe2299
What was the percentage change in Total (loan) in 2019 from 2018? Success: -6.38 1.331s
<< (828.8-885.3)/885.3 || [828.8, 885.3, -6.382017395233254] || [828.8, 885.3, 885.3] || True >>
1238d807-aa57-48a3-93b6-591873788625
What was the increase / (decrease) in the Statutory federal income tax (benefit) from 2018 to 2019? failure: -19411.0 good answer:  -19411  2.113s
<< 14,694 - 34,105 || [34105.0, 14694.0, -19411.0] || [14694.0, 34105.0] || True >>
ef9d4839-5277-4614-bb73-f902fd8a38b6
What was the average Tax exempt interest income? failure: -168.0 good answer:  -168  0.646s
<< - (197 + 101 + 206) / 3 || [-168.0] || [] || True >>
fec503e8-6f91-483e-856d-bb1278bd031f
What was the percentage change in the Domestic manufacturers deduction from 2017 to 2018? Success: -162.15 1.770s
<< -2,545 / 4,095 - 1 || [4095.0, -2545.0, -162.15] || [4095.0] || True >>
a3e21403-222e-4328-8f7d-9383d2d91fe9
What is the average dividend yield in 2017 and 2018? failure: 4.3999999999999995 good answer:  4.35  0.675s
<< (4.1% + 4.6%)/2  || [] || [4.1, 4.6, 2.0] || False >>
a3637ae4-b286-44a5-a115-83867e4bb14e
What is the average dividend yield in 2018 and 2019? failure: 4.4 good answer:  4.55  0.635s
<< (4.6% + 4.5%)/2  || [4.3999999999999995] || [4.6, 4.5, 2.0] || False >>
d3f04ae4-ced9-446d-87b7-bb9d193e3603
What is the average expected volatility in 2017 and 2018? failure: 27.9 good answer:  27.9  1.141s
<< (27.1% + 28.7%)/2  || [27.1, 28.7, 27.9] || [27.1, 28.7, 2.0] || False >>
8b6a4479-3b77-4db7-a90c-8b1ca41a8997
What was the change in net debt from 2018 to 2019? Success: 59.4 1.172s
<< 295.2-235.8 || [295.2, 235.8, 59.39999999999998] || [295.2, 235.8] || True >>
7b2b17a9-6409-45fb-907f-270832305974
What was the percentage change in net debt from 2018 to 2019? Success: 25.19 1.729s
<< (295.2-235.8)/235.8 || [295.2, 235.8, 25.190839694656475] || [295.2, 235.8, 235.8] || True >>
3b5bb347-41c7-499a-b044-87b9a04b0833
What was the percentage change in Total Other in 2018 from 2017? Success: 15.85 2.270s
<< (95-82)/82 || [89.0, 95.0, 82.0, 15.853658536585366] || [95.0, 82.0, 82.0] || True >>
*** Overall EM:  0.6545454545454545 / 30
0d0c77cf-d32c-4b0e-8da0-dcaa3f681f59
What is the percentage of Bell Wireless out of the Total BCE operating revenues in Q4 2019? failure: 39.47 good answer:  39.47  1.698s
<< 2,493/6,316 || [6316.0, 2493.0, 39.47118429385687] || [2493.0, 6316.0] || True >>
259e18e8-4738-4f4d-b625-e352ca78a136
What is the increase / (decrease) in the recorded investment from 2018 to 2019? Success: -8736.0 1.253s
<< 22,446 - 31,182 || [31182.0, 22446.0, -8736.0] || [22446.0, 31182.0] || True >>
407d43ea-c405-4b88-95ae-d15b1f25fb25
What is the average Specific allowance for credit losses? Success: 198.5 1.151s
<< (177 + 220) / 2 || [177.0, 220.0, 198.5] || [177.0, 220.0] || True >>
681dcc0f-a32e-46ca-9785-1289a6aba802
What is the percentage increase / (decrease) in the Net financing receivables from 2018 to 2019? Success: -28.05 1.534s
<< 22,224 / 30,890 - 1 || [30890.0, 22224.0, -28.054386532858533] || [22224.0, 30890.0] || True >>
d2969c34-708e-4ab0-8e21-32c0b18c544c
What is the ratio of current deferred revenue to non-current deferred revenue as of end of period? failure: 1.301684088269454 good answer:  1.3  1.389s
<< 4,483/3,444 || [4483.0, 3444.0] || [4483.0, 3444.0] || True >>
59f13f19-4494-4c54-8e9a-1b499d50021a
What is the total price of shares that were exercised or canceled between 2016 and 2017? failure: 0 good answer:  981341.34  2.115s
<< (235,514*2.92)+(81,794*3.59)  || [0, 0, 0] || [2.92, 3.59] || False >>
b382a11b-749b-425a-a77d-20e943e00f77
What is the proportion of granted shares between 2017 and 2018 over outstanding shares at September 30, 2017? failure: 0.0 good answer:  0.11  2.351s
<< 299,397/2,845,866  || [0, 0, 2845866.0, 0, 0.0] || [299397.0, 2845866.0] || False >>
741f8b2e-9312-4426-893d-69b99fab247b
What is the price of outstanding shares on September 30, 2019? failure: 7.0 good answer:  11808314  0.673s
<< 1,686,902*7.00  || [] || [1686902.0, 7.0] || False >>
cf89ffee-b551-4e34-9321-30325df32cc1
What was the change in the Amount recognized in other comprehensive (loss) income from 2017 to 2018? Success: -17.0 1.790s
<< -7 - 10 || [10.0, -7.0, -17.0] || [10.0] || True >>
147f7c09-a627-4719-93ad-33661b5a4543
What was the change in Total interest expense, net presented in the consolidated statements of income in which the effects of cash flow hedges are recorded between 2017 and 2018? Success: -2.0 1.713s
<< 138-140 || [140.0, 138.0, -2.0] || [138.0, 140.0] || True >>
6a441650-9d8a-43a0-8906-bec97a73ca2c
What is the total special termination benefits charge in 2018 and 2019? Success: 21.0 1.189s
<< 6+15 || [21.0] || [6.0, 15.0] || False >>
eb1ecc18-e3d3-4dd6-a689-546998eb2784
What is the percentage change in interest cost in 2019 from 2018? Success: 11.22 1.567s
<< (436-392)/392 || [436.0, 392.0, 11.224489795918368] || [436.0, 392.0, 392.0] || True >>
8a21f821-eaf6-421a-8c67-795e7e2d1f61
What was the percentage change in Adjusted EBITDA between 2018 and 2019? Success: 16.36 1.745s
<< (108,307-93,081)/93,081 || [108307.0, 93081.0, 16.357795898196194] || [108307.0, 93081.0, 93081.0] || True >>
07ec204e-3922-4b5c-b1fd-9cb9311a53e5
What was the percentage change in the Total net deferred tax assets between 2018 and 2019? Success: -22.26 1.249s
<< (14,158-18,211)/18,211 || [18211.0, 14158.0, -22.25577947394432] || [14158.0, 18211.0, 18211.0] || True >>
f1034ee7-b182-48d5-bad8-1d9902500f57
What is the difference in the number of rights 'granted during the period' between 2018 and 2019? failure: -1226114.0 good answer:  1226114  1.142s
<< 5,691,731 - 4,465,617  || [5691731.0, 4465617.0, -1226114.0] || [5691731.0, 4465617.0] || True >>
*** Overall EM:  0.6571428571428571 / 40
545cb01f-9b10-4a1b-8a7c-e9e74e725b26
What is the average number of rights 'outstanding at end of period' for 2018 and 2019? Success: 12085176.0 1.463s
<< (13,477,758 + 10,692,594)/2  || [10692594.0, 13477758.0, 12085176.0] || [13477758.0, 10692594.0] || True >>
*** Overall EM:  0.6619718309859155 / 40
cc053817-3496-48b3-9bfc-83e9ba71bb57
What is the percentage increase in the number of rights 'outstanding at the start of period' from 2018 to 2019?  Success: 58.71 1.546s
<< (10,692,594 - 6,737,076)/6,737,076  || [6737076.0, 10692594.0, 58.712681881575925] || [10692594.0, 6737076.0, 6737076.0] || True >>
*** Overall EM:  0.6666666666666666 / 40
fda3b0cb-bc87-4cbc-bc8f-79604538a700
What is the average Legal reserve within Appropriation of earnings? Success: 835623.0 0.865s
<< (707,299+963,947) / 2 || [707299.0, 963947.0, 835623.0] || [707299.0, 963947.0] || True >>
8d8c9fb6-6316-4fad-881e-7cdb3cfa965a
What is the increase/ (decrease) in Legal reserve within Appropriation of earnings from 2018 to 2019? Success: 256648.0 1.082s
<< 963,947-707,299 || [707299.0, 963947.0, 256648.0] || [963947.0, 707299.0] || True >>
b4aabd48-5010-425f-be30-c63f1c648c85
What is the increase/ (decrease) in Cash dividends within Appropriation of earnings from 2018 to 2019? Success: 2849050.0 1.782s
<< 9,765,155-6,916,105 || [6916105.0, 9765155.0, 2849050.0] || [9765155.0, 6916105.0] || True >>
f12806ca-aa4c-4fe6-84fc-10cefca76a9e
What is the change in the operating revenue under continuing operations from 2018 to 2019? Success: -22772.0 2.428s
<< 154,159-176,931 || [154159.0, 176931.0, -22772.0] || [154159.0, 176931.0] || True >>
f36e5912-f63c-4837-a9ed-ddbe73e5148b
What is the percentage of the operating leases of more than 5 years in the total operating leases? Success: 12.02 1.518s
<< 11,825/98,389 || [98389.0, 11825.0, 12.018619967679314] || [11825.0, 98389.0] || True >>
7ff6facd-1f7b-471c-9e38-5177c4eac9ba
What is the percentage of capital leases in the total liabilities? failure: 1.25 good answer:  0.62  0.927s
<< 50,049/8,031,229 || [100098.0, 8031229.0, 1.2463596791972933] || [50049.0, 8031229.0] || False >>
d13b3204-0428-41af-8e4a-771dde352c50
What is the percentage of the purchase obligations of more than 5 years in the total purchase obligations? Success: 8.64 1.209s
<< 36,675/424,561 || [424561.0, 36675.0, 8.638334656268475] || [36675.0, 424561.0] || True >>
e1ae4755-8038-4862-9f2f-b4197f9f2159
What was the increase / (decrease) in the contractual obligation for operating leases from 2020 to 2021-2022? Success: 2968.0 1.507s
<< 7,111-4,143  || [4143.0, 7111.0, 2968.0] || [7111.0, 4143.0] || True >>
eb50d3aa-16da-4087-9ab2-10106ebd10e7
What is the average annual Operating leases contractual obligations for 2020-2024? failure: 4859.25 good answer:  2988  2.575s
<< (4,143+7,111+3,686)/5 || [4143.0, 7111.0, 3686.0, 4497.0, 19437.0, 4859.25] || [4143.0, 7111.0, 3686.0] || True >>
61451090-3f7b-4fb1-b405-64a786d937d8
What was the increase / (decrease) in the asset retirement obligation from 2021-2022 to 2022-2023? Success: 100.0 1.697s
<< 250-150 || [150.0, 250.0, 100.0] || [250.0, 150.0] || True >>
56a014a9-5b9c-41e5-9523-ebbd3a01dd6d
What is the increase/ (decrease) in Statutory Audit, Certification, Audit of Individual and Consolidated Financial Statements from the period 2018 to 2019? Success: -451500.0 1.705s
<< 4,105,000-4,556,500 || [4105000.0, 4556500.0] || [4105000.0, 4556500.0] || True >>
2af4c7cf-79a2-4bdf-81b8-dbaff5081bc3
What is the increase/ (decrease) in Audit-Related Fees from the period 2018 to 2019? Success: 35071.0 1.169s

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [11]:
res

[{'prompt_version': 'V18',
  'start_cluster': None,
  'end_cluster': None,
  'start_global': datetime.datetime(2026, 3, 28, 23, 25, 46, 941048),
  'end_global': datetime.datetime(2026, 3, 28, 23, 25, 50, 220728)},
 {'prompt_version': 'V23',
  'start_cluster': datetime.datetime(2026, 3, 28, 23, 26, 1, 937431),
  'end_cluster': datetime.datetime(2026, 3, 28, 23, 26, 8, 386517),
  'start_global': datetime.datetime(2026, 3, 28, 23, 26, 8, 386532),
  'end_global': datetime.datetime(2026, 3, 28, 23, 37, 45, 621257)},
 {'prompt_version': 'V41',
  'start_cluster': datetime.datetime(2026, 3, 28, 23, 37, 45, 621277),
  'end_cluster': datetime.datetime(2026, 3, 28, 23, 37, 58, 66638),
  'start_global': datetime.datetime(2026, 3, 28, 23, 37, 58, 66651),
  'end_global': datetime.datetime(2026, 3, 28, 23, 49, 39, 185486)},
 {'prompt_version': 'V43c',
  'start_cluster': datetime.datetime(2026, 3, 28, 23, 49, 39, 185504),
  'end_cluster': datetime.datetime(2026, 3, 28, 23, 49, 54, 747065),
  'start_global': datetime.datetime(2026, 3, 28, 23, 49, 54, 747080),
  'end_global': datetime.datetime(2026, 3, 29, 0, 1, 54, 552729)},
 {'prompt_version': 'V29',
  'start_cluster': datetime.datetime(2026, 3, 29, 0, 1, 54, 552762),
  'end_cluster': datetime.datetime(2026, 3, 29, 0, 2, 4, 44867),
  'start_global': datetime.datetime(2026, 3, 29, 0, 2, 4, 44880),
  'end_global': datetime.datetime(2026, 3, 29, 0, 14, 45, 663111)},
 {'prompt_version': 'V31',
  'start_cluster': datetime.datetime(2026, 3, 29, 0, 14, 45, 663131),
  'end_cluster': datetime.datetime(2026, 3, 29, 0, 14, 57, 436949),
  'start_global': datetime.datetime(2026, 3, 29, 0, 14, 57, 436963),
  'end_global': datetime.datetime(2026, 3, 29, 0, 27, 25, 544397)},
 {'prompt_version': 'V44b',
  'start_cluster': datetime.datetime(2026, 3, 29, 0, 27, 25, 544417),
  'end_cluster': datetime.datetime(2026, 3, 29, 0, 27, 40, 159377),
  'start_global': datetime.datetime(2026, 3, 29, 0, 27, 40, 159391),
  'end_global': datetime.datetime(2026, 3, 29, 0, 40, 44, 164344)}]

In [6]:
res = [{'prompt_version': 'V18',
  'start_cluster': None,
  'end_cluster': None,
  'start_global': datetime.datetime(2026, 3, 28, 23, 25, 46, 941048),
  'end_global': datetime.datetime(2026, 3, 28, 23, 25, 50, 220728)},
 {'prompt_version': 'V23',
  'start_cluster': datetime.datetime(2026, 3, 28, 23, 26, 1, 937431),
  'end_cluster': datetime.datetime(2026, 3, 28, 23, 26, 8, 386517),
  'start_global': datetime.datetime(2026, 3, 28, 23, 26, 8, 386532),
  'end_global': datetime.datetime(2026, 3, 28, 23, 37, 45, 621257)},
 {'prompt_version': 'V41',
  'start_cluster': datetime.datetime(2026, 3, 28, 23, 37, 45, 621277),
  'end_cluster': datetime.datetime(2026, 3, 28, 23, 37, 58, 66638),
  'start_global': datetime.datetime(2026, 3, 28, 23, 37, 58, 66651),
  'end_global': datetime.datetime(2026, 3, 28, 23, 49, 39, 185486)},
 {'prompt_version': 'V43c',
  'start_cluster': datetime.datetime(2026, 3, 28, 23, 49, 39, 185504),
  'end_cluster': datetime.datetime(2026, 3, 28, 23, 49, 54, 747065),
  'start_global': datetime.datetime(2026, 3, 28, 23, 49, 54, 747080),
  'end_global': datetime.datetime(2026, 3, 29, 0, 1, 54, 552729)},
 {'prompt_version': 'V29',
  'start_cluster': datetime.datetime(2026, 3, 29, 0, 1, 54, 552762),
  'end_cluster': datetime.datetime(2026, 3, 29, 0, 2, 4, 44867),
  'start_global': datetime.datetime(2026, 3, 29, 0, 2, 4, 44880),
  'end_global': datetime.datetime(2026, 3, 29, 0, 14, 45, 663111)},
 {'prompt_version': 'V31',
  'start_cluster': datetime.datetime(2026, 3, 29, 0, 14, 45, 663131),
  'end_cluster': datetime.datetime(2026, 3, 29, 0, 14, 57, 436949),
  'start_global': datetime.datetime(2026, 3, 29, 0, 14, 57, 436963),
  'end_global': datetime.datetime(2026, 3, 29, 0, 27, 25, 544397)},
 {'prompt_version': 'V44b',
  'start_cluster': datetime.datetime(2026, 3, 29, 0, 27, 25, 544417),
  'end_cluster': datetime.datetime(2026, 3, 29, 0, 27, 40, 159377),
  'start_global': datetime.datetime(2026, 3, 29, 0, 27, 40, 159391),
  'end_global': datetime.datetime(2026, 3, 29, 0, 40, 44, 164344)}]

In [7]:
pd.DataFrame(res)

,prompt_version,start_cluster,end_cluster,start_global,end_global
0,V18,NaT,NaT,2026-03-28 23:25:46.941048,2026-03-28 23:25:50.220728
1,V23,2026-03-28 23:26:01.937431,2026-03-28 23:26:08.386517,2026-03-28 23:26:08.386532,2026-03-28 23:37:45.621257
2,V41,2026-03-28 23:37:45.621277,2026-03-28 23:37:58.066638,2026-03-28 23:37:58.066651,2026-03-28 23:49:39.185486
3,V43c,2026-03-28 23:49:39.185504,2026-03-28 23:49:54.747065,2026-03-28 23:49:54.747080,2026-03-29 00:01:54.552729
4,V29,2026-03-29 00:01:54.552762,2026-03-29 00:02:04.044867,2026-03-29 00:02:04.044880,2026-03-29 00:14:45.663111
5,V31,2026-03-29 00:14:45.663131,2026-03-29 00:14:57.436949,2026-03-29 00:14:57.436963,2026-03-29 00:27:25.544397
6,V44b,2026-03-29 00:27:25.544417,2026-03-29 00:27:40.159377,2026-03-29 00:27:40.159391,2026-03-29 00:40:44.164344

In [30]:
res_e = []
for row in res:
    if row['start_cluster'] and row['end_cluster']:
        start = pd.Timestamp(row['start_cluster']).tz_localize("Europe/Budapest")
        end = pd.Timestamp(row['end_cluster']).tz_localize("Europe/Budapest")
        (wh_counter, wh_gauge_sum,wh_trap, delta ) = energy.fetch_gpu_wh(start, end,  "2s")
        res_e.append({"prompt_version": row["prompt_version"], "start": start, "end": end, "type": "cluster", "wh_counter": wh_counter, "wh_trap": wh_trap, "delta": delta,  "delta_us": delta, "delta_min": delta/(1000000*60), "avg_wh_counter": (wh_counter/delta)*1000000*3600,"avg_wh_trap": (wh_trap/delta)*1000000*3600 })
    if row['start_global'] and row['end_global']:
        start = pd.Timestamp(row['start_global']).tz_localize("Europe/Budapest")
        end = pd.Timestamp(row['end_global']).tz_localize("Europe/Budapest")
        (wh_counter, wh_gauge_sum,wh_trap, delta ) = energy.fetch_gpu_wh(start, end,  "2s")
        res_e.append({"prompt_version": row["prompt_version"], "start": start, "end": end, "type": "global", "wh_counter": wh_counter, "wh_trap": wh_trap,  "delta": delta, "delta_us": delta, "delta_min": delta/(1000000*60), "avg_wh_counter": (wh_counter/delta)*1000000*3600 ,"avg_wh_trap": (wh_trap/delta)*1000000*3600 }  )
pd.DataFrame(res_e)

,prompt_version,start,end,type,wh_counter,wh_trap,delta,delta_us,delta_min,avg_wh_counter,avg_wh_trap
0,V18,2026-03-28 23:25:46.941048+01:00,2026-03-28 23:25:50.220728+01:00,global,0.0,0.046111,3279680.0,3279680.0,0.054661,0.000000,50.614694
1,V23,2026-03-28 23:26:01.937431+01:00,2026-03-28 23:26:08.386517+01:00,cluster,1.0,0.710833,6449086.0,6449086.0,0.107485,558.218637,396.800415
2,V23,2026-03-28 23:26:08.386532+01:00,2026-03-28 23:37:45.621257+01:00,global,81.0,81.433333,697234725.0,697234725.0,11.620579,418.223576,420.460986
3,V41,2026-03-28 23:37:45.621277+01:00,2026-03-28 23:37:58.066638+01:00,cluster,1.0,1.410833,12445361.0,12445361.0,0.207423,289.264409,408.103871
4,V41,2026-03-28 23:37:58.066651+01:00,2026-03-28 23:49:39.185486+01:00,global,82.0,81.257222,701118835.0,701118835.0,11.685314,421.041320,417.227416
5,V43c,2026-03-28 23:49:39.185504+01:00,2026-03-28 23:49:54.747065+01:00,cluster,2.0,1.634167,15561561.0,15561561.0,0.259359,462.678519,378.046907
6,V43c,2026-03-28 23:49:54.747080+01:00,2026-03-29 00:01:54.552729+01:00,global,84.0,83.903611,719805649.0,719805649.0,11.996761,420.113402,419.631327
7,V29,2026-03-29 00:01:54.552762+01:00,2026-03-29 00:02:04.044867+01:00,cluster,1.0,0.946111,9492105.0,9492105.0,0.158202,379.262556,358.824518
8,V29,2026-03-29 00:02:04.044880+01:00,2026-03-29 00:14:45.663111+01:00,global,88.0,88.568611,761618231.0,761618231.0,12.693637,415.956429,418.644128
9,V31,2026-03-29 00:14:45.663131+01:00,2026-03-29 00:14:57.436949+01:00,cluster,1.0,1.225000,11773818.0,11773818.0,0.196230,305.763177,374.559892
10,V31,2026-03-29 00:14:57.436963+01:00,2026-03-29 00:27:25.544397+01:00,global,88.0,86.887500,748107434.0,748107434.0,12.468457,423.468590,418.115081
11,V44b,2026-03-29 00:27:25.544417+01:00,2026-03-29 00:27:40.159377+01:00,cluster,1.0,1.660556,14614960.0,14614960.0,0.243583,246.322946,409.032936
12,V44b,2026-03-29 00:27:40.159391+01:00,2026-03-29 00:40:44.164344+01:00,global,91.0,91.721944,784004953.0,784004953.0,13.066749,417.854503,421.169533

In [45]:
for (prompt_version, results_file, errors_file, cluster_id) in runs:
    #print(prompt_version, errors_file, cluster_id)
    error_cluster_qids = list(pd.read_csv(errors_file).query(f'cluster == {cluster_id}')['qid'])
    print(prompt_version, len(error_cluster_qids))

V23 7
V41 8
V43c 10
V29 6
V31 7
V44b 7